Stunner - remove Powermock dependency from designer and stunner framework
kiegroup/kie-wb-common pull request #3317
Opened 2020-06-01 11:40 UTC by hasys

Hi @romartin, @LuboTerifaj, @domhanak,

there are changes with Powermock removals. I tried to do it as gentle as possible, but still think it is OK to postpone merge of this PR after closest release cut.

But it is ready for review from code point of view. Full Downstream Build binaries can wait because we have only 10 builds allowed now for kie-wb-common Full Downstream and there are more urgent PRs available now (see [BXMSPROD-803](https://issues.redhat.com/browse/BXMSPROD-803) for more details).

Anyway let's check my changes on the code level and fix all your suggestions before start Full Downstream.

Thank you!

2020-06-03 21:59 UTC, romartin commented
as already commented guys, please let's postpone this review until next week, as we're actually other priorities around the next release.

Thanks!

2020-06-15 09:34 UTC, hasys commented
Hi @romartin, 7.8 is branched and I fixed conflict with master branch, so PR is ready for review again. Thank you!

2020-06-16 15:25 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
Why did you remove the test? Would it be possible to rewrite the test without using Power Mockito?

2020-06-16 15:25 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
Why did you remove the test? Would it be possible to rewrite the test without using Power Mockito?

2020-06-16 15:25 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
Why did you remove the test? Would it be possible to rewrite the test without using Power Mockito?

2020-06-16 15:32 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindableDefinitionAdapterTest.java
> -    public void testGetProperty() {
Why did you remove the test?

2020-06-16 15:32 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindableDefinitionAdapterTest.java
> -    public void testGetNameField() {
Why did you remove the test?

2020-06-16 15:32 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindablePropertySetAdapterTest.java
> -    public void testGetProperty() {
Why did you remove the test?

2020-06-17 13:58 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 13:58 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 14:00 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 14:02 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 14:02 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 14:02 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 14:04 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindableDefinitionAdapterTest.java
> -    public void testGetNameField() {
It was testing getter without any logic, I don't think we need to write tests like this in general. But to rewrite this one we need to do some addition code manipulation which will increase risks of regression so I don't think rewriting this test worth it.

2020-06-17 14:17 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindablePropertySetAdapterTest.java
> -    public void testGetProperty() {
I reverted this test removal, great catch, thank you!

2020-06-17 14:17 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindableDefinitionAdapterTest.java
> -    public void testGetProperty() {
I reverted this test removal, great catch, thank you!

2020-06-17 15:36 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramServiceTest.java
> -    public void testGetAll() {
Well, it looks like it tests more about Files and Paths, than about our classes, and it is not so easy to rewrite. Will try it tomorrow. Thank you!

2020-06-17 16:07 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramServiceTest.java
> -    public void testGetAll() {
Just finished and this Tests removal is reverted. Thank you!

2020-06-17 16:07 UTC, hasys commented
Hi @LuboTerifaj, @romartin,

all questions answered/addressed. PR is ready for review again. Thank you!

2020-06-17 16:07 UTC, hasys commented
Jenkins execute full downstream build

2020-06-18 09:23 UTC, hasys commented
Hi @LuboTerifaj, @romartin,

Sonar Cloud failind due to 2 of 4 branches covered:
![image](https://user-images.githubusercontent.com/1477262/85002993-e45f2a80-b155-11ea-8755-e997b0e0c50f.png)
so I am testing for `nulls` which is the most important in my oppinion, and parameters aren't `nulls` we need to mock static method invocation. It will need addition refactoring but won't improve overall coverage in my oppinion, so I think it is fine to have the most important paths (can cause NullPointer) covered. WDYT?  

test fails in Full downstream build doesn't related to this PR:

<details>
  <summary>Failed tests</summary>
  <pre>

org.kie.processmigration.it.ProcessMigrationIntegrationTest.testReadinessCheck
--------------------------------------------------------------------------------------------------------------------------------------

Error Message

Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

Stacktrace

org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.testReadinessCheck(ProcessMigrationIntegrationTest.java:114)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.testReadinessCheck(ProcessMigrationIntegrationTest.java:114)

org.kie.processmigration.it.ProcessMigrationIntegrationTest.testMigration
--------------------------------------------------------------------------------------------------------------------------------------

Error Message

Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

Stacktrace

org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.createPlan(ProcessMigrationIntegrationTest.java:179)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.createMigration(ProcessMigrationIntegrationTest.java:148)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.testMigration(ProcessMigrationIntegrationTest.java:134)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.createPlan(ProcessMigrationIntegrationTest.java:179)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.createMigration(ProcessMigrationIntegrationTest.java:148)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.testMigration(ProcessMigrationIntegrationTest.java:134)

org.kie.processmigration.it.ProcessMigrationIntegrationTest.testLivenessCheck
-------------------------------------------------------------------------------------------------------------------------------------

Error Message

Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

Stacktrace

org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.testLivenessCheck(ProcessMigrationIntegrationTest.java:108)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.kie.processmigration.it.ProcessMigrationIntegrationTest.testLivenessCheck(ProcessMigrationIntegrationTest.java:108)

</pre>
</details>

PR is ready for review. Thank you!

2020-06-19 00:00 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindingUtilsImpl.java
> +public class ClientBindingUtilsImpl {
No need for this if not changing `ClientBindingUtils`

2020-06-19 00:02 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationEditorWidgetViewImpl.java
> +    protected void ok() {
really need for changing it to `protected`?

2020-06-19 00:02 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationEditorWidgetViewImpl.java
> +    protected void hide() {
really need for changing it to `protected`?

2020-06-19 00:02 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentEditorWidgetViewImpl.java
> +    protected void initTypeSelector() {
really need for changing it to `protected`?

2020-06-19 00:02 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentEditorWidgetViewImpl.java
> +    protected void ok() {
really need for changing it to `protected`?

2020-06-19 00:02 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentEditorWidgetViewImpl.java
> +    protected void hide() {
really need for changing it to `protected`?

2020-06-23 07:23 UTC, hasys commented on kie-wb-common-dmn/kie-wb-common-dmn-client/pom.xml
> +    <dependency>
Yes, you are right, DMN modules were transitively dependent on PowerMock and used it, so without this declaration DMN tests will start fail with PowerMock not found.

2020-06-23 07:24 UTC, hasys commented on kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/pom.xml
> +      <groupId>org.powermock</groupId>
same, some tests failing in DMN after powermock removal from Stunner dependencies.

2020-06-23 07:33 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
> +    protected void walkFileTree(final org.uberfire.java.nio.file.Path root, SimpleFileVisitor<org.uberfire.java.nio.file.Path> fileVisitor) {
With package private, test fails with:
```
[ERROR] testGetAll(org.kie.workbench.common.stunner.project.backend.service.ProjectDiagramServiceControllerTest)  Time elapsed: 0.021 s  <<< ERROR!
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 

Misplaced argument matcher detected here:

-> at org.kie.workbench.common.stunner.core.backend.service.AbstractVFSDiagramServiceTest.testGetAll(AbstractVFSDiagramServiceTest.java:332)
-> at org.kie.workbench.common.stunner.core.backend.service.AbstractVFSDiagramServiceTest.testGetAll(AbstractVFSDiagramServiceTest.java:332)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.
```

2020-06-23 07:37 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
> +    protected org.uberfire.backend.vfs.Path convertToBackendPath(final org.uberfire.java.nio.file.Path path) {
With package private there is a failing test:
```
[ERROR] testGetAll(org.kie.workbench.common.stunner.project.backend.service.ProjectDiagramServiceControllerTest)  Time elapsed: 0.025 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at org.kie.workbench.common.stunner.core.backend.service.AbstractVFSDiagramServiceTest.testGetAll(AbstractVFSDiagramServiceTest.java:322)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed
```

2020-06-23 07:39 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
> +    protected org.uberfire.java.nio.file.Path convertToNioPath(final org.uberfire.backend.vfs.Path path) {
With package private there is a failing test:
```
[ERROR] testGetAll(org.kie.workbench.common.stunner.project.backend.service.ProjectDiagramServiceControllerTest)  Time elapsed: 0.013 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at org.kie.workbench.common.stunner.core.backend.service.AbstractVFSDiagramServiceTest.testGetAll(AbstractVFSDiagramServiceTest.java:321)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed
```

2020-06-23 07:42 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindableDefinitionAdapter.java
> +    protected <T, R> R getProxiedValue(final T pojo,
Fixed, thank you!

2020-06-23 07:45 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationEditorWidgetViewImpl.java
> +    protected void ok() {
It leads to the following test issues:
```
[ERROR] Errors: 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testCreateAndClose(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.setUp:157 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testCreateAndClose » UnfinishedStubbing 
Unfinish...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testCreateAndSave(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.setUp:157 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testCreateAndSave » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testCreateAndSaveEmpty(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.setUp:157 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testCreateAndSaveEmpty » UnfinishedStubbing 
Unfi...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testGetNameHeader(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.setUp:157 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testGetNameHeader » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testReadOnly(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.setUp:157 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testReadOnly » UnfinishedStubbing 
Unfinished stu...
```

2020-06-23 07:48 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationEditorWidgetViewImpl.java
> +    protected void hide() {
Otherwise there are following tests failing:
```
[ERROR] Errors: 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testCreateAndClose(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.testCreateAndClose:279 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testCreateAndClose » UnfinishedStubbing 
Unfinish...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testCreateAndSave(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.testCreateAndSave:246 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testCreateAndSave » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest.testCreateAndSaveEmpty(org.kie.workbench.common.stunner.bpmn.client.forms.fields.notificationsEditor.widget.NotificationEditorWidgetTest)
[ERROR]   Run 1: NotificationEditorWidgetTest.testCreateAndSaveEmpty:220 » NullPointer
[ERROR]   Run 2: NotificationEditorWidgetTest.testCreateAndSaveEmpty » UnfinishedStubbing 
Unfi...
```

2020-06-23 07:50 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentEditorWidgetViewImpl.java
> +    protected void initTypeSelector() {
Otherwise following tests starts to fail:
```
[ERROR] Errors: 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndClose(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:123 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndClose » UnfinishedStubbing 
Unfinish...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndSave(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:123 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndSave » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndSaveEmpty(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:123 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndSaveEmpty » UnfinishedStubbing 
Unfi...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testGetNameHeader(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:123 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testGetNameHeader » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testReadOnly(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:123 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testReadOnly » UnfinishedStubbing 
Unfinished stu...
```

2020-06-23 07:51 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentEditorWidgetViewImpl.java
> +    protected void ok() {
Otherwise following issues will be during test execution:
```
[ERROR] Errors: 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndClose(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:125 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndClose » UnfinishedStubbing 
Unfinish...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndSave(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:125 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndSave » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndSaveEmpty(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:125 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndSaveEmpty » UnfinishedStubbing 
Unfi...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testGetNameHeader(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:125 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testGetNameHeader » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testReadOnly(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.setUp:125 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testReadOnly » UnfinishedStubbing 
Unfinished stu...
```

2020-06-23 07:54 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentEditorWidgetViewImpl.java
> +    protected void hide() {
Otherwise following tests will fail:
```
[ERROR] Errors: 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndClose(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.testCreateAndClose:219 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndClose » UnfinishedStubbing 
Unfinish...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndSave(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.testCreateAndSave:195 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndSave » UnfinishedStubbing 
Unfinishe...
[INFO] 
[ERROR] org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest.testCreateAndSaveEmpty(org.kie.workbench.common.stunner.bpmn.client.forms.fields.reassignmentsEditor.widget.ReassignmentEditorWidgetTest)
[ERROR]   Run 1: ReassignmentEditorWidgetTest.testCreateAndSaveEmpty:175 » NullPointer
[ERROR]   Run 2: ReassignmentEditorWidgetTest.testCreateAndSaveEmpty » UnfinishedStubbing 
Unfi...

```

2020-06-23 08:30 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindingUtils.java
> +    private static ClientBindingUtilsImpl utils = new ClientBindingUtilsImpl();
The difference between `AbstractVFSDiagramService` and `ClientBindingUtils` is `ClientBindingUtils` is static class without instances, so we can't mock one of it's methods without PowerMock, but AbstractVFSDiagramService isn't a static class and we have instance of it, so we can mock one of it's methods.

But I think we can create DataBinder wrapper which by default will transfer calls to Errai or can be mocked if needed. Will it be better? WDYT?

2020-06-23 08:30 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/definition/adapter/binding/ClientBindingUtilsImpl.java
> +public class ClientBindingUtilsImpl {
Will it be better if it will be replaced by `DataBinder` wrapper?

2020-06-24 12:38 UTC, hasys commented
Jenkins retest please

2020-07-02 11:24 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
> +    protected void walkFileTree(final org.uberfire.java.nio.file.Path root, SimpleFileVisitor<org.uberfire.java.nio.file.Path> fileVisitor) {
oops ok

2020-07-02 11:25 UTC, hasys commented
Jenkins retest please

2020-10-19 09:03 UTC, hasys commented
Hi @romartin, more PowerMock/GwtMock tests where added meanwhile on client side so I didn't remove PowerMock dependency entirely, I rebased to the master and kept only safe changes so we can merge it fast and finish removal as separate effort if needed. Thank you!

2020-10-19 09:03 UTC, hasys commented
jenkins do cdb

2020-10-21 13:32 UTC, romartin commented
ok @hasys thanks ,lemme know when this is ready to merge! :+1:

2020-10-23 12:38 UTC, LuboTerifaj requested changes
Hello @hasys ,

A new code has been added since this PR was opened. Therefore there are places in the code where the powermock hasn't been removed yet.
Can you please have a look at it?

See also my comments inline.

Thanks!

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramServiceTest.java
> -    public void testGetAll() {
The test hasn't been added back yet.

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
It doesn't test just a basic getter within one class. Therefore I wouldn't remove this test.

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
It doesn't test just a basic getter within one class. Therefore I wouldn't remove this test.

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
It doesn't test just a basic getter within one class. Therefore I wouldn't remove this test.

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
It doesn't test just a basic getter within one class. Therefore I wouldn't remove this test.

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
It doesn't test just a basic getter within one class. Therefore I wouldn't remove this test.

2020-10-23 12:38 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
It doesn't test just a basic getter within one class. Therefore I wouldn't remove this test.

2020-10-23 13:30 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
It doesn't have name setter, but it is, just go one level inside and you will see it:
```java
    @Override
    public Connection getSourceConnection() {
        Point2D sourcePosition = PropertyReaderUtils.getSourcePosition(definitionResolver,
                                                                       element.getId(),
                                                                       getSourceId());
        return MagnetConnection.Builder
                .at(sourcePosition.getX(),
                    sourcePosition.getY())
                .setAuto(PropertyReaderUtils.isAutoConnectionSource(element));
    }
```

All logic concentrates in two methods:
```java
PropertyReaderUtils.getSourcePosition(definitionResolver, element.getId(), getSourceId());
... and ...

PropertyReaderUtils.isAutoConnectionSource(element);
```

But as you can see both of them are mocked:
```java
PowerMockito.when(PropertyReaderUtils.getSourcePosition(definitionResolver, ASSOCIATION_ID, SOURCE_ID)).thenReturn(position);
PowerMockito.when(PropertyReaderUtils.isAutoConnectionSource(association)).thenReturn(arbitraryBoolean);
```

So all logic in the called method is mocked and not executed.

If you check remaining code in the called method you will see that tested code is a "setter" but with different name - `at` which calls constructor and set values in it also without performing of any logic. Than value verified by `result.getLocation()` which is classic Get method without any logic. So we have classic `get` and `set` test, but in this case `set` is renamed to `at`. And all logic mocked by PowerMock and not executed anyway.

I don't see much value in such tests especially if it creates significant maintenance cost.

Next point that my next task (in one or two weeks from now) is start work on marshallers replacement, which makes unit tests even less valuable (but not functional tests which aren't affected by my pr).

2020-10-23 13:31 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
Same as https://github.com/kiegroup/kie-wb-common/pull/3317/files#r510884726

2020-10-23 13:34 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
Even more obvious than https://github.com/kiegroup/kie-wb-common/pull/3317/files#r510884726 it just called mocked getter:
```java

    // Test (pay attention to PowerMockito.when):
    @Test
    @SuppressWarnings("unchecked")
    public void testGetControlPoints() {
        List<Point2D> controlPoints = mock(List.class);
        mockStatic(PropertyReaderUtils.class);
        PowerMockito.when(PropertyReaderUtils.getControlPoints(definitionResolver, ASSOCIATION_ID)).thenReturn(controlPoints);
        assertEquals(controlPoints, propertyReader.getControlPoints());
    }

   // Checked method:
    @Override
    public List<Point2D> getControlPoints() {
        return PropertyReaderUtils.getControlPoints(definitionResolver,
                                                    element.getId());
    }
```

2020-10-23 13:42 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetSourceConnection() {
See https://github.com/kiegroup/kie-wb-common/pull/3317/files#r510884726

2020-10-23 13:43 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetTargetConnection() {
Same as https://github.com/kiegroup/kie-wb-common/pull/3317/files#r510884726

2020-10-23 13:43 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/AssociationPropertyReaderTest.java
> -    public void testGetControlPoints() {
Same as https://github.com/kiegroup/kie-wb-common/pull/3317/files#r510884726

2020-10-23 13:56 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramServiceTest.java
> -    public void testGetAll() {
Returned with refactoring

2020-10-23 14:00 UTC, hasys commented
Hi @LuboTerifaj,

thank you for your review. Good point about `AbstractVFSDiagramServiceTest.java`. This commit was lost during rebasing. See https://github.com/kiegroup/kie-wb-common/pull/3317#issuecomment-711883187

Main idea was that this PR is very old and we starting to wast time on it on infinite rebases. Also as you pointed out there are already some new PowerMock tests arrived. So idea was to cherry-pick only safe test changes/removal. And mentioned by you wasn't so safe since it contains some refactoring as well. Any way it was already tested and no issues where found so I rebased it as well.

I think all points are solved now. Please give this PR a priority it is very expensive infinitely rebase it again and again.

Thank you @LuboTerifaj for great job! :)

2020-10-23 14:00 UTC, hasys commented
jenkins do cdb

2020-10-26 09:51 UTC, hasys commented
jenkins do cdb

2020-10-26 12:57 UTC, hasys commented
Hi @romartin, I rebased PR to master again. I suggest to merge the PR without PR approval this time.

Tests for declarative code with `Cyclomatic complexity == 1` just tests nothing but take time to write and maintain. Also in this particular case `Cyclomatic complexity == 1` tests will also decrease code design quality since will require an ugly refactoring: creating non-static wrappers for static utility methods. So by continuing as QE suggests will needs:

1. Decrease quality of code design
2. Investment in test writing and support with very low to non addition value

I think after all rebases and retests already invested it is time to merge it as is or just close the PR and related jira issue as won't do. I don't think this change worth addition investments. What do you think?

Thank you!

2020-10-26 14:53 UTC, romartin commented
looks good to me @hasys . Please @LuboTerifaj take this into account so we can close this maintaince task as soon as possible. Thanks!

2020-10-29 14:43 UTC, LuboTerifaj reviewed
Hello @hasys ,

I agree with removing the tests as we discussed on gchat and the meeting.

However, the acceptance criteria are not met:

- The repo is not fully cleared from PowerMock dependency.

Would it be possible to remove it?

Thank you!

2020-11-09 15:12 UTC, hasys commented
jenkins do cdb

2020-11-10 13:11 UTC, hasys commented
Hi @LuboTerifaj, as I mentioned in https://github.com/kiegroup/kie-wb-common/pull/3317#issuecomment-711883187 and in https://github.com/kiegroup/kie-wb-common/pull/3317#issuecomment-715360570 this task won't close the Jira issue entirely (see comments why) just first step towards closing it.

2020-11-11 11:26 UTC, hasys commented
<details>
  <summary>Stack trace of Compile build failure</summary>
  <pre>groovy.lang.MissingPropertyException: No such property: owner for class: java.util.AbstractMap$SimpleImmutableEntry
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
    at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
    at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
    at githubscm.getForkedProjectName(githubscm.groovy:204)
    at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.find(CpsDefaultGroovyMethods:4061)
    at githubscm.getForkedProjectName(githubscm.groovy:204)
    at ___cps.transform___(Native Method)
    at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
    at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
    at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
    at sun.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
    at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
    at com.cloudbees.groovy.cps.Next.step(Next.java:83)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
    at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
    at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
    at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
    at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
    at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE</pre>
</details>

Issue is fixed now by https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/5c016699706abbc6d2a88f7cf1fecf6f1be749a0

jenkins do cdb

2020-11-12 03:05 UTC, hasys commented
<details>
  <summary>Random build issue</summary>
  <pre>13:17:43  [INFO] ------------------------------------------------------------------------
13:17:43  [INFO] BUILD FAILURE
13:17:43  [INFO] ------------------------------------------------------------------------
13:17:43  [INFO] Total time:  02:31 min (Wall Clock)
13:17:43  [INFO] Finished at: 2020-11-11T08:16:05-05:00
13:17:43  [INFO] ------------------------------------------------------------------------
13:17:43  [ERROR] Failed to execute goal on project google-tasks-workitem: Could not resolve dependencies for project org.jbpm.contrib:google-tasks-workitem:jar:7.46.0-SNAPSHOT: Could not transfer artifact com.google.http-client:google-http-client-jackson2:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar.part (No such file or directory) -> [Help 1]
13:17:43  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project google-tasks-workitem: Could not resolve dependencies for project org.jbpm.contrib:google-tasks-workitem:jar:7.46.0-SNAPSHOT: Could not transfer artifact com.google.http-client:google-http-client-jackson2:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar.part (No such file or directory)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:269)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:17:43      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
13:17:43      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
13:17:43      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
13:17:43      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:17:43      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
13:17:43      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
13:17:43      at java.lang.Thread.run (Thread.java:748)
13:17:43  Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.jbpm.contrib:google-tasks-workitem:jar:7.46.0-SNAPSHOT: Could not transfer artifact com.google.http-client:google-http-client-jackson2:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar.part (No such file or directory)
13:17:43      at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:209)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:17:43      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
13:17:43      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
13:17:43      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
13:17:43      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:17:43      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
13:17:43      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
13:17:43      at java.lang.Thread.run (Thread.java:748)
13:17:43  Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact com.google.http-client:google-http-client-jackson2:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar.part (No such file or directory)
13:17:43      at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)
13:17:43      at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:202)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
13:17:43      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
13:17:43      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:17:43      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
13:17:43      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
13:17:43      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
13:17:43      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
13:17:43      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
13:17:43      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
13:17:43      at java.lang.Thread.run (Thread.java:748)
13:17:43  Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.google.http-client:google-http-client-jackson2:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar.part (No such file or directory)
13:17:43      at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
13:17:43      at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver [...]

2020-11-19 15:34 UTC, LuboTerifaj approved these changes
It looks good to me. Thanks!

Just for the record, not all powermock dependencies have been removed in this PR.

2020-11-20 20:20 UTC, romartin commented
jenkins do cdb

2020-11-23 15:25 UTC, merged