KOGITO-2528 : Reuse Data Types across the process
kiegroup/kie-wb-common pull request #3347
Opened 2020-06-30 20:05 UTC by inodeman

Hi @romartin @LuboTerifaj this PR is just the data types, Data Objects code has been removed. After this is merged I can update Data Objects to use Data Types Service. Will upload War and VSCode extension. There is some Tests still to be written, will start on that and wait for Sonarcloud results as well. but as far as usability it can be tested now.

2020-06-30 20:06 UTC, inodeman commented
Jenkins execute full downstream build

2020-07-02 16:48 UTC, inodeman commented
Jenkins execute full downstream build

2020-07-02 16:49 UTC, inodeman commented
Jenkins retest please

2020-07-03 14:46 UTC, handreyrc commented
Hey @inodeman, I don't have access to War and VS Code extension you shared. 
Could you review the link permissions?
Thanks

2020-07-03 15:07 UTC, handreyrc commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/project/backend/service/service/FindDataTypesProjectServiceTest.java
> +        final List<String> dataTypeNames = service.getDataTypeNames(path, new ArrayList<>());
Hey @inodeman, I notice that here we are creating a new instance of arraylist to match the method signature. Maybe it would be better to pass null and check internally or perhaps overload the method. Just thinking.
WDYT?

2020-07-03 15:29 UTC, inodeman commented
Hi @handreyrc Permissions changed, try now https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing

2020-07-03 15:30 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/project/backend/service/service/FindDataTypesProjectServiceTest.java
> +        final List<String> dataTypeNames = service.getDataTypeNames(path, new ArrayList<>());
Hi @handreyrc sure, I am adding additional tests, will make the change

2020-07-03 19:27 UTC, handreyrc commented
Hey @inodeman, I could test and it works like a charm for me.
Great job!
Thanks

2020-07-03 19:35 UTC, inodeman commented
> Hey @inodeman, I could test and it works like a charm for me.
> Great job!
> Thanks

Good to hear @handreyrc thanks :-)

2020-07-03 19:36 UTC, inodeman commented
Jenkins retest please

2020-07-03 19:36 UTC, inodeman commented
Jenkins execute full downstream build

2020-07-06 17:34 UTC, inodeman commented
Jenkins retest please

2020-07-06 17:35 UTC, inodeman commented
Jenkins execute full downstream build

2020-07-07 18:25 UTC, inodeman commented
Jenkins execute full downstream build

2020-07-07 18:25 UTC, inodeman commented
Jenkins retest please

2020-07-08 15:05 UTC, inodeman commented
Jenkins retest please

2020-07-09 15:31 UTC, inodeman commented
Jenkins retest please

2020-07-10 20:53 UTC, inodeman commented
Jenkins retest please

2020-07-13 14:22 UTC, romartin commented
Jenkins retest please

2020-07-13 18:57 UTC, inodeman commented
Jenkins retest please

2020-07-14 16:52 UTC, inodeman commented
Jenkins retest please

2020-07-23 20:30 UTC, inodeman commented
Jenkins retest please

2020-07-23 20:31 UTC, inodeman commented
Jenkins execute full downstream build

2020-07-23 20:32 UTC, inodeman commented
Hi @romartin @handreyrc @domhanak change added for Data Objects, is ready for re-review. Basically now with Data Objects you can also create a new type that can be used in all other places.

2020-08-03 14:33 UTC, romartin commented
Hey @inodeman ,

Can you please rebase this? Thanks!

2020-08-03 14:34 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (doneLoading) {
why do we need this doneLoading flag, and also the timer? Looks tricky...

2020-08-03 14:35 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (isNullOrEmpty(value)) {
maybe this can be simplified using Streams in a single or couple of lines

2020-08-04 14:43 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (isNullOrEmpty(value)) {
Hi @romartin I got this code from another file. See here, let me know if I should convert to Streams 
![image](https://user-images.githubusercontent.com/39567766/89307653-91223800-d62e-11ea-8d59-e29d7406ad7a.png)

2020-08-04 14:44 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-04 14:45 UTC, inodeman commented
Hi @romartin I rebased, let me know about the above comments

2020-08-05 09:41 UTC, domhanak commented
jenkins execute full downstream build

2020-08-05 10:16 UTC, domhanak commented
@inodeman what should be checked for VSCode? I am not sure, JIRA does not provide much information.

2020-08-05 13:49 UTC, inodeman commented
Hi @domhanak let me check the issue you describe, also on VSCode you should have the same funcrionality, the data types of variables, data objects, imports, etc should e reusable, if you create one you can see it in other places. For instance if you crease Process Variable named "var2" of new type "com.myType.vars", "com.myType.vars" should be selectable in assignments, data Objects, etc and the same way if you create it in any of those places.

2020-08-06 07:42 UTC, domhanak commented
@inodeman Thanks, let me know. 

About VSCode, it only applies to regular types right? I am not aware of ability to create data type in KOGITO yet. Also, you are not sharing the .VSIX file, but whole folder which is a bit ineffective. Would it be possible to include just the vsix file?

2020-08-06 15:01 UTC, inodeman commented
Hi @domhanak, let me generate the artifacts again, the prior ones did not have the Data Objects, also about VSCode extension I will generate. About the issue you reported, I could not figure out why my changes affected it (About the populating the Process Variables after a delay) but seems it is an issue found in master, I also tested release jbpm-server-distribution-7.39.0.Final-dist and that same example and the same thing happens. This is the root cause, the first time the diagram is opened, there is a call to the Server which takes sometime, so after the forms are rendered, the Server replies with  the event and it forces refresh, that is why you see that. I could probably figure out a way to fix it, if you want to create a new ticket and assign it to me. I will upload artifacts in a few minutes.

2020-08-06 17:22 UTC, inodeman commented
Hi @domhanak new builds are uploaded to: https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing

2020-08-06 22:33 UTC, romartin commented
Hey @domhanak  @inodeman 

So there are 2 things to consider around the data types stuff:

- 1) Backend services - In case of BC, the data types are being populated from a backend service, rather than on Kogito, where no service will be used to retrieve data types (for now)

- 2) Reusing data types - It provides the ability to automatically populate data types drowdowns (on some different fields) as from the "custom" data types that the user has created during the authoring of the process.  The main usecase is for reusing custom data types, for example on different tasks, and just having to type it once, so once creating more tasks, the given custom data type will be also available to use (in the dropdowns). It WILL apply to both BC and Kogito, I mean on both places users can reuse data types

This PR in fact is only adding 2), as 1) is already implemented and working. Although it's true, that maybe this PR needs to manage both abilities, fetching async data from backend and reusing data types on the editor, in order to make both work propertly together.

@domhanak I've added you in the next checkpoint call, as I see you're also involved on the RHAPM release tasks, so if necessary, let's discuss that together in the call

@domhanak @inodeman My impression is that the way this feature should work is still not clear, as from @domhanak Qs above. So please let's try then to re-write the acceptance criteria for this and try to make it clear for everyone.

Thx!

2020-08-07 12:02 UTC, domhanak commented
@inodeman Thanks, I reported it here - https://issues.redhat.com/browse/JBPM-9279 

One question, should we prevent users from entering custom data types with lower case capital letters? Like `com.exampl.myType`?

2020-08-07 12:04 UTC, domhanak commented
@romartin I believe it is clear now, @inodeman provided everything I need. I tested the VSCode part and it is working as expected.
The only question I have now is in previous comment.

2020-08-07 12:17 UTC, domhanak commented
@inodeman So I run into some errors on VSCode, I am unable to access my data type in lots of place and there is a notification with `Error loading data types` shown.
1. Create a process with subprocess and human task
2. Create a process variable with custom type
3. Try to add Globalvariable, task I/O, Imports with this custom data type

2020-08-07 13:08 UTC, hasys commented
> One question, should we prevent users from entering custom data types with lower case capital letters? Like `com.exampl.myType`?

No, otherwise user won't be able to input valid Java identifier. Everything what is a valid FQN should be allowed even if it is not recommended to use it. We can show kind of warning that this kind of names is not recommended but I think it shouldn't be a part of this PR.

2020-08-07 21:22 UTC, inodeman commented
Hi @domhanak I checked the issue, unfortunately have not been able to reproduce it, I went to the steps you mention and was able to see the custom data type after saving and reloading.

Would it be a VS Code issue? I have 
![image](https://user-images.githubusercontent.com/39567766/89689477-b7abd180-d8c1-11ea-88d8-89cc833a0e81.png)
If it is possible you can record a short video and send it to me so I can replicate it, that would be great!

2020-08-07 23:10 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-12 08:13 UTC, domhanak commented
@inodeman Sure I will make a recording, but I am able to reproduce quite consistently. I also encountered more issues with `Error retrieving data types` notification

Here is the summary.

Issue 1 - Error pops up and the added type is not loaded in all places
1. Create new process and open properties panel
2. Open `Imports` and add a custom data type import with value `com.example.interface` or `com.example.default`
3. The notification `Error retrieving data types` will pop-up, twice
4. Navigate to Assignments, Data Objects,Imports,Multiple Instance and this notification will appear there too
5. You are unable to see the `com.example.default`in above locations too
Comments: If we allow types like this the process might not be compiled by kogito-extension as it will contain reserved words from java in types. Imho we could prevent this in editor, there was an issue recently with package name.

Issue 2 - The custom types are only visible in dropdowns they were added with
1. Use this file - https://gist.github.com/domhanak/5b238907dafbcab140de1d01e65b3ab6
2. There are 4 custom data types - `com.myspace.Dog`, `com.myspace.Fish`, `org.ujo.Bubak`, `org.ujo.santa`
3. Go to Process variables - Properties -> Process Data  - There is one variable `mister` with type `org.ujo.Bubak`
3.1. Open the dropdown and see only `org.ujo.Bubak`. There is no `com.myspace.Dog` or other type
4. Go to Global Variables - There is one variable `Pet` with type `org.ujo.santa`
4.1. Inspect dropdown and you will see only one custom data type `org.ujo.santa`
5. Go to sub-process's Data Assignments - There will be one named `ryba` with type `com.myspace.Fish`
5.1. Inspect the type dropdown and there will only be `com. myspace.Fish`
6. Go to Assignments of Task - There will be on Input assignment named `Z` with type `com.myspace.Dog`
6.1. Inspect the type dropdown and you will only see one data type `com.myspace.Dog`

This might be separate issue, but it could be connected to previous file.
7. Add a new custom data type in `Imports -> Data Types` the type won't be visible in other locations
8. Add a new custom data type in Assignments of Task -> the type will be accessible in other locations

2020-08-12 17:07 UTC, inodeman commented
Hi @domhanak let me recheck, just tested and did see some issues, some code change I did must have broken something, let me rework it, thanks for the findings! BTW, the pop up did you see them on Business Central or Kogito?

2020-08-13 08:21 UTC, domhanak commented
@inodeman Thanks. All I reported above is on VSCode, business-central worked for me without issues.

2020-08-13 15:06 UTC, inodeman commented
@LuboTerifaj btw, I think the builds from FDB are still there, at least yesterday they were, not sure if still today, if there are it is safe to test those. Let me know, otherwise I will upload later if the builds are ok in my local

2020-08-14 01:40 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (isNullOrEmpty(value)) {
well it's just a minor thing, it's more about the language declaration and styling than the results, once I see an iteration with some condition/s inside the loop, I just feel that it can could maybe be repsented using "functional" style rather than the "old" way, as it usually results on some more clear and easier code to read and understand. 
Anyway, it's just a really minor thing, nothing that could prevent this from being merged IMO.

2020-08-14 01:50 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (doneLoading) {
I don't have as much detail as you on this, so maybe just give my suggestions here, feel free to let me know if I'm wrong or something else prevents for doing this in some other way plz. 

I still don't see the need for a timer + flag to achieve this, looks not robust. Actually browsers and js engines provide different solutions for doing/managing sync/async remote calls, in a safe way, rather than assuming by ourselves the state for the call...

Again, I don't have all the context here, so maybe I'm wrong, but what about considering "encapsulating" the call in a javascript `Promise`?  This way, browser will manage the lifecycle for you and you can also check the promise status, and react when necessary. Also, depending on how you use the promise instance, notice by defintiion a Promise is only being called once. So if it applies, you can also improve the performance of the calls to this because it'll be done once, and browser ensures that, also ensures you'll get the _then_/_catch_ also being called properly. No need for any timer, no need for a flag, just need for the use of Promises properly, and let browser do this job.

WDYT?

Sorry for being a bit rude on this, but I think it's not completely safe to rely on this kind of solutions, although I'm open for dicussions, I know world is not ideal :)
Thanks anyway @inodeman , good job overall!! :+1:

2020-08-14 01:58 UTC, romartin commented
Hey @inodeman - I just added a single comment on the code side (timer + flag), so from the code perspective, rather than clatifying this, everything looks good to me.

Also please guys please there are is an urgent need to move this forward during next week, maybe if something is not clear from the user perspective also ask @lazarotti , as I'll be a few days off. I've been chatting with @inodeman and I think it's clear how it should behave from the engineers perspective, let us know if something is missing. I'll keep this a look and try to help on moving this forward anyway during the following days.

thanks a lot!
CC @inodeman @domhanak @lazarotti

2020-09-08 14:32 UTC, domhanak commented
@inodeman Hello, ping me when it is ready for retesting please :)

2020-09-08 14:45 UTC, inodeman commented
Hi @domhanak ,cleaning everything up now, so should send PR later today or tomorrow. Will let you know

2020-09-08 18:34 UTC, inodeman commented
Jenkins retest this

2020-09-08 18:35 UTC, inodeman commented
jenkins do fdb

2020-09-08 18:35 UTC, inodeman commented
Hi @domhanak ready for review from usability standpoint, sending this so that I can see Sonar Results for test to add. Will upload artifacts shortly.

2020-09-08 20:07 UTC, inodeman commented
Hi @domhanak here are the artifacts. https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing

2020-09-15 08:21 UTC, domhanak commented
@inodeman Hi, went throught the VSCode part. Every time I open process variables or any place where there are datatypes,   there is a `Error receiving datatypes` notification. Displayed like a lot of times, not just once.
I can't see data types from Task DI/DO in process variables and vice versa, I can only see datatypes that are relative to the task - context.
Basic use case - create data type in one dropdown and use it in different one doesn't work also existing custom data types are not correctly visible in other places where you can set data type.

2020-09-17 12:33 UTC, domhanak commented
@inodeman Hi, I tried again, with local build & then again with your .vsix,  I used processes from Mortgage examples and I couldn't reproduce anymore. So I will check again now.
@romartin @handreyrc Please add your reviews so we can get his in :)

2020-09-17 12:41 UTC, domhanak commented
@inodeman One issue in VSCode I notice is with the dropwdowns. They stay in `Custom...` state after I select them. Looks like visual bug only.
![Screenshot from 2020-09-17 14-37-39](https://user-images.githubusercontent.com/5937251/93471284-701e5980-f8f3-11ea-9342-3ed415bc0568.png)
1. Open properties, access process data and select a dropbox with DataType
2. Do not select anything, just close it
3. Dropbox stays showing `Customs...`
Workaround, reopen properties panel. Or any panel, modal the dropbox is in.

This is reproducible on all dropboxes - I can't reproduce in BC or Online editor for example.

2020-10-07 00:47 UTC, inodeman commented
Jenkins retest this

2020-10-07 00:47 UTC, inodeman commented
jenkins do fdb

2020-10-23 19:57 UTC, inodeman commented
jenkins do fdb

2020-10-23 19:57 UTC, inodeman commented
Jenkins retest this

2020-10-28 04:40 UTC, inodeman commented
jenkins do fdb

2020-10-28 04:41 UTC, inodeman commented
Jenkins retest this

2020-10-28 19:57 UTC, inodeman commented
jenkins do fdb

2020-10-28 19:57 UTC, inodeman commented
Jenkins retest this

2020-11-09 13:35 UTC, inodeman commented
jenkins do fdb

2020-11-09 13:35 UTC, inodeman commented
Jenkins retest this

2020-11-09 13:36 UTC, inodeman commented
Hi @romartin @lazarotti as discussed, Sonar issues are at 79%, but it can get tested for BC and Kogito. Let me know

2020-11-11 08:43 UTC, domhanak requested changes
Comments provided, please let me know @romartin Feel free to provide feedback on them too.
I am proceeding with e2e test, meanwhile this could be improved.

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +            // ToDo: Add extra types to be supported
let's throw some exception when we encounter this and let's  log the type that wasn't processed by these `if-else` branches.

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +public abstract class AbstractDataTypeCache {
Javadoc

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +    public void testExtractFromItem() {
I suggest to split this into smaler test cases. For each datatype we should have one test case.

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +    private ArrayList<String> defaultDataTypes = new ArrayList<>(Arrays.asList("MyType", "MyString", "MyObject"));
Could we please also test type that look like this `com.myspace.Person` or `org.native.common.logging.ParserWagon` Just to be sure.

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +        assertEquals(getLastItem(), "MyObject");
I notice we only check last item, would it be possible to check cases where we find more dataTypes in one definition?

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDirectDiagramMarshaller.java
> -        LOG.debug("Starting diagram unmarshalling...");
Why is this removed?

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +        assertEquals(getLastItem(), "MyObject");
Also, what if we extract same datatype form one definition? Can that happen? is the expected output one datatype or two datatypes?

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/processes/DataTypeCacheServerTest.java
> +    public void testCacheServer() {
please split this into multiple test cases,
1. Empty  diagram
2. Test with two nodes

I would also add check that verify that parent class `AbstractDataTypeCache` contains expected datatypes when the diagram is empty or has nodes with `dataIOSets`.

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        // ToDo: Can implement Flushing
todo

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/pom.xml
> +    <dependency>
can this be just removed?

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientMarshalling.java
> +        //  this.dataTypeNamesService = dataTypeNamesService;
commented code

2020-11-11 08:43 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
> +  <version>7.43.0-SNAPSHOT</version>
is this correct?

2020-11-12 12:44 UTC, domhanak commented
jenkins do fdb

2021-01-19 19:01 UTC, inodeman commented
jenkins do fdb

2021-01-20 20:01 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +            // ToDo: Add extra types to be supported
Hi @domhanak will throw Illegal Argument Exception

2021-01-20 20:03 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +public abstract class AbstractDataTypeCache {
Hi @domhanak JavaDoc added

2021-01-20 20:22 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +    public void testExtractFromItem() {
Hi @domhanak refactored and split now

2021-01-20 20:35 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +    private ArrayList<String> defaultDataTypes = new ArrayList<>(Arrays.asList("MyType", "MyString", "MyObject"));
Hi @domhanak added object "com.myspace.Person"

2021-01-20 21:04 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
> +        assertEquals(getLastItem(), "MyObject");
Hi @domhanak added additional tests, now testing 2 each time

2021-01-20 21:06 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDirectDiagramMarshaller.java
> -        LOG.debug("Starting diagram unmarshalling...");
@domhanak my mistake, readded

2021-01-20 21:07 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        // ToDo: Can implement Flushing
Hi @domhanak not needed for now, removed

2021-01-20 21:08 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/pom.xml
> +    <dependency>
Hi @domhanak removed

2021-01-20 21:09 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientMarshalling.java
> +        //  this.dataTypeNamesService = dataTypeNamesService;
Hi @domhanak removed

2021-01-20 21:10 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
> +  <version>7.43.0-SNAPSHOT</version>
@domhanak fixed

2021-01-20 21:12 UTC, inodeman commented
Jenkins retest this

2021-01-20 21:12 UTC, inodeman commented
jenkins do fdb

2021-01-21 08:47 UTC, domhanak commented
@inodeman Hi, the failed tests:
```
00:10:49  [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 84.066 s <<< FAILURE! - in org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT
00:10:49  [ERROR] testBasicModel(org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT)  Time elapsed: 33.107 s  <<< ERROR!
00:10:49  org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.className: docks-item-E-DiagramEditorPropertiesScreen (tried for 10 second(s) with 500 milliseconds interval)
00:10:49  	at org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.waitPropertiesAndExplorer(BPMNDesignerKogitoSeleniumIT.java:252)
00:10:49  	at org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.testBasicModel(BPMNDesignerKogitoSeleniumIT.java:181)
00:10:49  Caused by: org.openqa.selenium.NoSuchElementException: 
00:10:49  Cannot locate an element using By.className: docks-item-E-DiagramEditorPropertiesScreen
00:10:49  For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
00:10:49  Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
00:10:49  System info: host: 'rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.11.1.el7.x86_64', java.version: '1.8.0_275'
00:10:49  Driver info: driver.version: unknown
00:10:49  	at org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.waitPropertiesAndExplorer(BPMNDesignerKogitoSeleniumIT.java:252)
00:10:49  	at org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.testBasicModel(BPMNDesignerKogitoSeleniumIT.java:181)
00:10:49  
```
Could not open a diagram editor for new diagram. (empty content) Looks like you changes could be the cause. I see there is a screenshot that shows monaco text editor.

You can run these tests using `-Pkogito-it-tests` and you can also disable the headless mode if needed. All is in the pom.xml and README

2021-01-21 16:56 UTC, inodeman commented
Hi @domhanak , my apologies, still working on this, will let you know when ready for QA

2021-01-22 08:28 UTC, domhanak commented
Hi @inodeman sure, I am just raising awareness about this selenium test for kogito editor that we have here

2021-01-25 19:02 UTC, inodeman commented
Jenkins retest this

2021-01-25 19:02 UTC, inodeman commented
jenkins do fdb

2021-01-26 00:12 UTC, inodeman commented
Jenkins retest this

2021-01-26 00:12 UTC, inodeman commented
jenkins do fdb

2021-01-27 22:01 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/processes/DataTypeCacheServerTest.java
> +    public void testCacheServer() {
Hi @domhanak split into two now

2021-01-27 22:01 UTC, inodeman commented
Jenkins retest this

2021-01-27 22:01 UTC, inodeman commented
jenkins do fdb

2021-01-27 22:02 UTC, inodeman commented
Hi @domhanak @romartin PR is now testable, let me know your comments, I tested both BC and Kogito to ensure both work

2021-01-28 21:17 UTC, inodeman commented
Jenkins retest this

2021-01-28 21:18 UTC, inodeman commented
jenkins do fdb

2021-01-28 22:18 UTC, inodeman commented
Hi @domhanak I researched that issue, but I could not find anything my PR did, I checked last on master and it happens as well. See screenshot 
![image](https://user-images.githubusercontent.com/39567766/106205620-0143ed80-617c-11eb-9171-90452c10e8bf.png)
You can see it is on master branch (lower right) and the same test fails

2021-01-29 10:08 UTC, domhanak commented
@inodeman Ok, thanks will look into it.

2021-02-02 19:29 UTC, inodeman commented
Jenkins retest this

2021-02-02 19:30 UTC, inodeman commented
jenkins do fdb

2021-02-02 19:31 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +            // ToDo: Add extra types to be supported
Hi @domhanak this caused the issue that it could not open the diagram you mentioned, if execution reaches this else, it simply means that it does not contain a data type, so removing the throwing exception.

2021-02-08 20:33 UTC, inodeman commented
Jenkins retest this

2021-02-08 20:33 UTC, inodeman commented
jenkins do fdb

2021-02-08 20:33 UTC, inodeman commented
Hi @domhanak @romartin ready for review now :-)

2021-02-09 08:01 UTC, domhanak commented
jenkins retest this

2021-02-09 08:01 UTC, domhanak commented
jenkins do fdb

2021-02-10 10:27 UTC, domhanak commented
jenkins retest this

@inodeman WAR or VSIX? :) Build fails, will review after the build is green and there is one :heavy_check_mark: from @romartin  or @handreyrc

2021-02-10 10:42 UTC, hasys commented
@inodeman, @domhanak,

looks like known issue with OptaPlanner which is under investigation. Can't find ticket right now, but I think I saw some discussions about it.

<details>
  <summary>Error log</summary>
  <pre>08:19:18  [INFO] ------------------------------------------------------------------------
08:19:18  [INFO] BUILD FAILURE
08:19:18  [INFO] ------------------------------------------------------------------------
08:19:18  [INFO] Total time:  24.103 s
08:19:18  [INFO] Finished at: 2021-02-09T03:16:11-05:00
08:19:18  [INFO] ------------------------------------------------------------------------
08:19:18  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project optaplanner-core: Compilation failure: Compilation failure: 
08:19:18  [ERROR] /home/jenkins/workspace/KIE/master/fdb/kie-wb-common-master.fdb/kiegroup_optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java:[226,26] wrong number of type arguments; required 2
08:19:18  [ERROR] /home/jenkins/workspace/KIE/master/fdb/kie-wb-common-master.fdb/kiegroup_optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java:[310,22] wrong number of type arguments; required 2
08:19:18  [ERROR] -> [Help 1]
08:19:18  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project optaplanner-core: Compilation failure
08:19:18      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
08:19:18      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
08:19:18      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
08:19:18      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
08:19:18      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
08:19:18      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
08:19:18      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
08:19:18      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
08:19:18      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
08:19:18      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
08:19:18      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
08:19:18      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
08:19:18      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
08:19:18      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
08:19:18      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
08:19:18      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
08:19:18      at java.lang.reflect.Method.invoke (Method.java:498)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
08:19:18  Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
08:19:18      at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
08:19:18      at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
08:19:18      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
08:19:18      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
08:19:18      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
08:19:18      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
08:19:18      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
08:19:18      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
08:19:18      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
08:19:18      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
08:19:18      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
08:19:18      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
08:19:18      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
08:19:18      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
08:19:18      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
08:19:18      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
08:19:18      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
08:19:18      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
08:19:18      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
08:19:18      at java.lang.reflect.Method.invoke (Method.java:498)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
08:19:18      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
08:19:18  [ERROR] 
08:19:18  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
08:19:18  [ERROR] 
08:19:18  [ERROR] For more information about the errors and possible solutions, please read the following articles:
08:19:18  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
08:19:18  [ERROR] 
08:19:18  [ERROR] After correcting the problems, you can resume the build with the command
08:19:18  [ERROR]   mvn <args> -rf :optaplanner-core</pre>
</details>

2021-02-17 20:48 UTC, inodeman commented
jenkins retest this

2021-02-17 20:48 UTC, inodeman commented
jenkins do fdb

2021-02-18 19:58 UTC, inodeman commented
jenkins retest this

2021-02-18 19:58 UTC, inodeman commented
jenkins do fdb

2021-02-19 17:36 UTC, inodeman commented
Hi @romartin @handreyrc can you look at the code and provide a review for this? Thanks a bunch

2021-02-22 22:26 UTC, inodeman commented
Hi @romartin @domhanak artifacts can be found here https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing|

2021-02-23 07:19 UTC, domhanak commented
Hi @inodeman , below there are my findings from VSCode:

- in this screenshot you can see duplicate datatype `AgeDecisonService`, once as FQDN and once in `AgeDecisionService [package]` fromat

![Screenshot from 2021-02-23 08-11-43](https://user-images.githubusercontent.com/5937251/108812124-d8621d00-75ae-11eb-82bd-35c78686105d.png)

For process variable there is only one:
![Screenshot from 2021-02-23 08-15-22](https://user-images.githubusercontent.com/5937251/108812379-4e668400-75af-11eb-9ecb-a793b8a40807.png)


- When you add custom data type to process variables, it is changed back to Object upon confirmation. I need to select the dropdown again to reselect my custom type.
               1. Create a new process variable (name it first and then create custom data type)
               2. Confirm the variable (click somewhere in editor, ENTER does not work)
               3. The dropwdown with type is Object and not custom data type
               
This is what I encountered so far, will let you know about more as soon as I find something.

2021-02-23 13:48 UTC, domhanak commented
@inodeman about the https://gist.github.com/domhanak/f8b5c3917d85ea0084ff0338117e21cd and notifications... I am not sure what is the issue here. So far it looks like it happens when there is a default Java object in Imports - Float, Object etc but I can't confirm yet. Will keep investigating, let me know if you can reproduce and also please let me know about the issues from previous comment.

2021-02-24 21:00 UTC, inodeman commented
Hi @domhanak thanks for this, will work on fixing the issues

2021-02-25 22:28 UTC, inodeman commented
jenkins retest this

2021-02-25 22:28 UTC, inodeman commented
jenkins do fdb

2021-02-25 22:30 UTC, inodeman commented
Hi @domhanak, the 3 issues mentioned have been fixed. Please find the new artifacts here. https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing , @romartin can you review?

2021-03-01 07:49 UTC, domhanak commented
@inodeman I can still reproduce  the issue with `Error retrieving data types` dialog when I open a process that has `default` Java types in imports. 

**Issue  1**
STEPS
1. Add some custom types to `Imports`
2. Save and reopen -> no error dialogs
3. Add some `default` data type to imports (Object, String)
4. Save and reopen.
5. Access properties panel, imports, data assignemmt -> error dialog shows


**Issue  2**
Another issue that I now notice is the behavior with creating custom data type in process variables, data I/O dropdowns.
STEPS
1. Open a process with custom data types and process variables already set.
2. Navigate to process variables and try changing type of one variable ( Soup in this picture)
![Screenshot from 2021-03-01 08-43-10](https://user-images.githubusercontent.com/5937251/109466596-42c10480-7a6a-11eb-97bd-8c013f5e4129.png)
3. Click the dropdown and notice the edited custom data type is missing in it. (org.ext.kitchen.Soup is missing in the list)
![Screenshot from 2021-03-01 08-43-10](https://user-images.githubusercontent.com/5937251/109466700-6be19500-7a6a-11eb-9dc7-2d4f76c6d67f.png)
4. Decide not to change the type and click somewhere outside to cancel operation.
5. The data type box stays in `Custom...` state
![image](https://user-images.githubusercontent.com/5937251/109466812-9af80680-7a6a-11eb-8e4f-575b6dea8769.png)

Workaround is to close the panel and the expected datatype `org.ext.kitchen.Soup` will be back in the list and shown as usual:
![image](https://user-images.githubusercontent.com/5937251/109466931-c0851000-7a6a-11eb-8533-ababf7a83b1f.png)

**Issue  3**
Not sure this is issue, ( AC do not define anything) but I as able to create duplicate custom data type:
![image](https://user-images.githubusercontent.com/5937251/109467104-f629f900-7a6a-11eb-8505-680edf5def8f.png)

2021-03-01 12:38 UTC, romartin reviewed
Hey @inodeman 

Added a few more review comments on the code, please take a look.

Thanks!

2021-03-01 12:38 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +    public void extractFromItem(View view) {
it can be `static`

2021-03-01 12:38 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        } else {
no need for this empty `else` block, isn't it?

2021-03-01 12:38 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDirectDiagramMarshaller.java
> +            dataTypeCache.initCache(diagramRoot);
why the cache relies on the `BpmnNode` instance? This is an eclipse model object, not our internal model object. I would prefer, if possible, to always rely on our models, so we can populate the cache any time, whitout the need for having the eclipse models being parsed as well.
WDYT?

2021-03-01 12:38 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (doneLoading) {
hey @inodeman , I still see the use of the gwt timer here. Could you please consider my comment above? Lemme know what you think

2021-03-01 12:38 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorWidgetViewImpl.java
> +        new Timer() {
another gwt timer here?

2021-03-01 12:55 UTC, domhanak commented
@inodeman I have discovered another issue in business-central:
When I add custom datatype import and confirm it. The datatype is malformed.

STEPS
1. Open MortgageProcessAppropval from sample project
2. Navigate to imports
3. Import a known data type - Applicantion and confirm.
4. Open any dropdown with datat types. You will see the following malformed datatype:
![Screenshot from 2021-03-01 13-54-48](https://user-images.githubusercontent.com/5937251/109499870-ba585900-7a95-11eb-9d08-764ab24a88e9.png)

2021-03-02 07:57 UTC, domhanak commented
@inodeman Hello, so I confirmed several more issues in BC:

* Data Types are not populated.
STEPS
1. Open MortgageProcess sample and open the MortgageApprovalProcess
2. Navigate to Process Variables and add new variable
3. Open the dropdown, not all data objects are there
![Screenshot from 2021-03-02 08-41-23](https://user-images.githubusercontent.com/5937251/109614724-4b314200-7b33-11eb-9af8-2c81ded86609.png)
All data objects in the project are:
![Screenshot from 2021-03-02 08-43-30](https://user-images.githubusercontent.com/5937251/109614837-6e5bf180-7b33-11eb-8174-592332bd3323.png)

* Unable to build project in business-central when external dependency added.
 So I see this as an ultimate use case in BC for this feature and it is not working. If I properly add the external data type into my process via Imports I will constantly see following errors when I build the project or when the process is saved:
 
![Screenshot from 2021-03-02 08-57-08](https://user-images.githubusercontent.com/5937251/109616321-51c0b900-7b35-11eb-9955-7c70ca1ac92f.png)

2021-03-02 21:02 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +    public void extractFromItem(View view) {
Hi @romartin changed now

2021-03-02 21:03 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        } else {
Hi @romartin removed

2021-03-02 21:06 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDirectDiagramMarshaller.java
> +            dataTypeCache.initCache(diagramRoot);
Hi @romarting, if you could explain more, as far as I can see it is from our models. See 
![image](https://user-images.githubusercontent.com/39567766/109715124-7b430a00-7b60-11eb-92da-2ecb61d66ce0.png) let me know

2021-03-02 21:10 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorWidgetViewImpl.java
> +        new Timer() {
Hi @romartin on the first timer, I use it to give enough time for the DataNameService to return the DataTypes, let me know what else can I use. On second instance if I do not set the timer, when it looses focus it does not get set right, let me know

2021-03-02 23:14 UTC, inodeman commented
jenkins retest this

2021-03-02 23:14 UTC, inodeman commented
jenkins do fdb

2021-03-02 23:16 UTC, inodeman commented
Hi @domhanak please find new builds at https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing.
The issues mentioned have been fixed except

1) About Duplicates on Imports. Currently it is not implemented, I wil check to see if there is an easy way to do it.
2) Issue mentioned about Project not building on BC when an external import is present. I checked on master and the same thing happens.

Let me know, all the best!

2021-03-04 08:25 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/importsEditor/popup/editor/defaultImport/DefaultImportsEditorWidgetTest.java
> +    public void testAddDataTypesFromImports() {
Can we also add test for adding data types from Process Variable dropdown, Global Variables dropdown, Task Data I/O dropdown? Or did I miss it? 

Also the values you use here, I suggest changing them to something actually used - `com.myspace.DataTypeOfTypes`

2021-03-04 08:29 UTC, domhanak commented
@inodeman Duplicate imports reported here - https://issues.redhat.com/browse/KOGITO-4580

Reported another issue about editing and deleting custom data types - https://issues.redhat.com/browse/KOGITO-4582
Should be triaged by leads.

Looks good to me now, I wasn't able to reproduce issues I found previously, please check my comment about additional test cases for what I discovered during review. But it might be possible I missed it, just link the cases in a reply please. 

Let me know and I can provide approval. Thanks!

2021-03-04 08:29 UTC, domhanak commented
jenkins retest this

2021-03-04 10:03 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        }
One suggestion here, let me know if it valid. I understand that if we add some new instance and we forget to add it here we won't be able to extract the data types from it.

```suggestion
        } else {
            // log error that we tried to extract data type for a definition we did not know about?
        }
```

2021-03-04 10:10 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        if (definition instanceof DataObject) {
@inodeman I think we have missed some nodes here. For example `IntermediateLinkEvent`
When you open a process with node that is missing in this `if-else` tree the data type won't be extracted.

Imho the `AbstractDataTypeCacheTest` needs to be extended for every possible node we have in our BPMN editor that can set Data Types in some way.

2021-03-04 18:21 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        }
Hi @domhanak basically what it does it goes through all the nodes and checks instances, if it is not from the list it does not do anything, so if it reaches else, it is not really an error, it is just a node that does not contain data types

2021-03-04 19:21 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        if (definition instanceof DataObject) {
Hi @domhanak added IntermediateLinkEvent, also added tests for it

2021-03-04 19:36 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/importsEditor/popup/editor/defaultImport/DefaultImportsEditorWidgetTest.java
> +    public void testAddDataTypesFromImports() {
Hi @domhanak I added imports since it is basically the same mechanism for all, there is also tests for calling the service. I changed Test 1 and Test 2 now. Let me know

2021-03-04 22:54 UTC, inodeman commented
jenkins retest this

2021-03-04 22:54 UTC, inodeman commented
jenkins do fdb

2021-03-04 23:13 UTC, inodeman commented
Hi @domhanak @romartin new builds here. https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing, applied changes requested. @romartin was able to remove one timer entirely and the second one I could only change it to deferredCommand, let me know

2021-03-05 09:02 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
> +        }
Maybe some info in that case?

2021-03-05 15:01 UTC, domhanak commented
@inodeman I tried following scenario in VSCode again and it did not work now:

You can reproduce by opening this process - https://gist.github.com/domhanak/dec157f58b385d62379d43f16da7b163
It contains `object, float, integer, boolean, string` data types in imports, custom data types will not load on process variable dropdown. I isolated it to `Float` data type.

So it looks like the issue is solely when there is `Float` as data type in any assignment - can be: Import, ProcessVariable, DataIO etc.
Steps I followed:
1. Create a new process, model something, I used the process linked above.
2. Add custom data type as import.
3. Verify you can see it in Process Variables dropdown and other relevant dropdowns.
4. Add a process variable as with `Float` datatype OR add Import of `Float` OR set data assignment with `Float` datatype.
5. You can still see your custom datatype in selection of dropdowns
6. Save & reopen
7. Try adding new variable or data assignme - , dropdown will not contain custom data type
8. Change the float data type to something else
9. Save & reopen
10. The custom data type should be seen in dropdowns

2021-03-05 18:58 UTC, inodeman commented
Hi @domhanak thanks, let me check it out, maybe the latest changes broke this

2021-03-08 18:36 UTC, inodeman commented
jenkins retest this

2021-03-08 18:37 UTC, inodeman commented
jenkins retest this

2021-03-08 18:37 UTC, inodeman commented
jenkins do fdb

2021-03-09 09:01 UTC, domhanak commented
@inodeman Would it be possible to add tests for the issues I have described before? I see changes to services but I do not see any changes on its tests.

Latest VSCode artifact does not work for me. I tried default scenario with `kie-kjar-archetype`:

1. Open a maven project (structure is as when you generate ti with `kie-kjar-archetype`)
2. Create process in `src/main/resources` 
3. Define some layout (start->usertask->end)
4. Create process variable with custom type
5. Navigate to User Tasks assignments, tie datatype is not there.

Results:
- Process Variables and Global Variables show only data types created there. They do not show custom types created anywhere else.
- Imports only shows custom data type in the row it was created in.
- TaskDataInputs only show custom data types created in inputs.
- TaskaDataOutputs only show custom data types created in outputs.

NOTE: I tried reinstalling a couple of times and for some short time the data types were showing all across process but later it was only limited to the area you were creating the data type in. By Area I mean (Imports, Task DataInputs, TaskaDataOutputs, Process Variables, Global Variables)

Opening existing complex process also did not work as expected.
I was only able to access custom data types in respective area:
- Process Variables were showing custom data types only  from all process variables.
- Imports were showing only one data type, the one that was created in that row.
- Global Variables were showing custom data types only from all global variables
- TaskDataInputs were showing custom data types only from TaskDataInputs
- TaskDataInputs were showing custom data types only from TaskDataOutputs

Not sure why is this happening now,  but if I work on my business application and normally develop my process the data type feature breaks. After it gets broken it stays that way. Reload of VSCode does not work.
I also tried uninstalling and reinstalling the extension and that did not help.
@inodeman let me know if you can reproduce this.

Will start checking business-central now...

2021-03-09 09:22 UTC, domhanak commented
In business central experienced these issues:

*Issue 1 - Unexpected error dialog popup when I click on TaskDataInput, TaskDataOutput, Import, Process Variable, GlobalVariable because of duplicate*  `Float` 
![Screenshot from 2021-03-09 10-09-45](https://user-images.githubusercontent.com/5937251/110446699-bf359200-80bf-11eb-889e-0bae20c01ce8.png)

1. Open MortagageProcessApproval
2. Open Imports, close it.
3. Try adding data type to some area
4. Unexpected error dialog appears

*Issue 2 - Dropdown box is back to `Custom..` value after editting it*

1. Select  a custom data type from dropdown
2. Confirm it and see the box

![Screenshot from 2021-03-09 10-14-26](https://user-images.githubusercontent.com/5937251/110447444-877b1a00-80c0-11eb-8249-14bff3538c26.png)


*Issue 3 - Data Types are shown as empty some times*
![Screenshot from 2021-03-09 10-19-36](https://user-images.githubusercontent.com/5937251/110447938-04a68f00-80c1-11eb-91a1-2171bdd6e007.png)

1. Model process for a bit, save & reopen, add types, variables

*Issue 4 - Unable to see all data types in process from project`
I can see `ValidationErrorDo` for example in MortgageApprovalProcess

Custom data types seems to work, but the regular data types from projects (custom but created using BC) do not.

2021-03-10 21:31 UTC, inodeman commented
jenkins retest this

2021-03-10 21:31 UTC, inodeman commented
jenkins do fdb

2021-03-10 21:32 UTC, inodeman commented
Hi @domhanak fixed BC and Kogito Issues, it should be fine now, also added tests for the service you mentioned. Ready for review @romartin no timers now. Artifacts can be found here. https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing

2021-03-11 20:20 UTC, romartin commented
ok thanks for the updates @inodeman 
please @domhanak feel free to go ahead with the review again!
Thanks guys!

2021-03-12 08:09 UTC, domhanak commented
@romartin I still do not see this approved from engineering side, what if you ask for changes? Given the numerous re-reviews on this PR. I will wait for your approval first.

2021-03-12 09:39 UTC, domhanak commented
@inodeman @romartin There is an issue with multiple projects in business central. 

*Issue 1*
1. User is able to see data types from non-dependent projects.
Steps:
1. Have one project. Create some data type in it. `com.Solo`
2. Create a process and use the data type in an Import, Process Variable etc.
3. Save & close.
4. Create a new project.
5. Create a process, check any data type drop-down, see `com.Solo` in suggestions
Expected results: `com.Solo` is not suggested as it is a data type from different project and the project has no dependency on it.

*Issues 2*
2. User is able to see data types from deleted  projects.
Steps:
1. Have one project. Create some data type in it. `com.Solo`
2. Create a process and use the data type in an Import, Process Variable etc.
3. Save & close.
4. Delete the project.
5. Create a new project.
6. Create a process, check any data type drop-down, see `com.Solo` in suggestions
Expected results: When a project is deleted, it's data types are not suggested in other projects.

Let me know how to handle these.

*Issue 3*
Another thing is that according to JIRA:
`When a new data type is created or existing one is edited, the changes apply on all places within one process.`

But I am unable to do this in Business central:
1. Create a data objects named `com.example.Tomato`
2. Create a process and import this data object to process and save it.
3. Rename data object to `TomatoRenamed`
4. See the import of your process, there is a data type named `Tomato` it did not update.
5. Inspect the import and see the `TomatoRenamed` there with `Tomato` which does not exist anymore.
Expected results: The Import, Process variable data type is updated with renamed data type and the old data type occurence is deleted.

Issues 3 is also relevant on VSCode, I already reported it here but didn't see any comments  - https://issues.redhat.com/browse/KOGITO-4582

2021-03-12 20:17 UTC, romartin commented
Hey @domhanak 
I already did review on the code side, and I was asking to replace timers. Those have been already replaced, so I'll start with the review on the UI, I'll provide feedback ASAP..

2021-03-16 11:12 UTC, domhanak commented
@romartin Checked with 7.48.x I am able to edit the custom data types. I will let you know about master once I manage to download it :D

2021-03-16 21:28 UTC, romartin commented
hey  @domhanak 

THanks for your feedback again, appreciated!!

Sooo I've been discussing this with @inodeman and I think we found the root cause for some issues. The thing is that on BC it looks the data types "cache" being implemented is "global", so cache is visible for all processes, which is not correct. So first thing we're going to fix is moving this cache to dependant scope, not global, this way each process will have its own cache, as expected. (Please @inodeman let us know when this is resolved and we'll check again)

Once this is resolved, we'lcontinue with other issues, if still apply or are not regressions, and also finally trying to filter out the data types per each procect, once calling the service.

So my suggestion is fixing this in 2 steps:
1.- FIxing the scope for the caches in BC (also please ensure kogito doesn't get broke)
2.- Filtering out data types per project
3- Fixing any other edge case or issue you can find guys

Does that sounds good???

THanks both guys! Let's do last sprint to see if we can get this merged ASAP, remember we only have a week more for the cut-off

Thanks!

2021-03-19 19:36 UTC, inodeman commented
jenkins retest this

2021-03-19 19:37 UTC, inodeman commented
jenkins do fdb

2021-03-19 19:39 UTC, inodeman commented
Hi @domhanak @romartin you can find new artifacts here. https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing, I fixed the scope issue which will solve most major previous issues. The issue about renaming and the change broadcasting to all types is pending, it might be more tricky than expected. Also, now you can rename data types in Process, Global Variables and Assignments. Data Objects and Imports is doable when initially created, after that they are not, happens also in master. Trying to figure out if I should enable renaming in them in this ticket or not, what do you think @romartin ?

2021-03-22 07:47 UTC, domhanak commented
Hello @inodeman 
I tried following basic use case in Business central and it did not work.
Create a process and:
1. Add custom data type into (import, ...) any possible place.
2. Check the data type in (Imports, ...) any other place where it was not added.
3. The data type is not visible in other places, but it should be.

Data objects from project worked well. Custom data types are not visible across the process.
This is the basic use case, is there any test that verifies this on unit/integration level? Could you please link it? If there is no such test please add it if possible.

2021-03-22 09:04 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/ActivityDataIOEditor.java
> +    public void addDataType(String dataType, String oldType) {
this method does not seem to be covered in tests

2021-03-22 09:06 UTC, domhanak commented
@inodeman Also, please check -https://sonarcloud.io/component_measures?id=org.kie.workbench%3Akie-wb-common&pullRequest=3347&metric=new_coverage&view=list lots of new code that is added without any coverage.

2021-03-22 09:24 UTC, domhanak commented
@inodeman I tried basic use case in business central and it did not work;

1. Add custom data type to Imports. (com.tomato.Tomato)
2. Confirm and navigate to process variables.
3. Try selecting the `com.tomato.Tomato`. It is not offered.

2021-03-22 14:11 UTC, romartin commented
thanks @domhanak for your tesing agian.

hey @inodeman Please test carefully the PR once delivering any commi, it looks the basic use case is broken again and that's causing our resources to spend time here.
Please can you take a look again at all possible use case cases? test all them, fix whatever is necessary, and let us know when the build is ready and safe for testing again.
Thanks!

2021-03-23 22:00 UTC, inodeman commented
jenkins retest this

2021-03-23 22:00 UTC, inodeman commented
jenkins do fdb

2021-03-24 15:59 UTC, inodeman commented
jenkins retest this

2021-03-24 15:59 UTC, inodeman commented
jenkins do fdb

2021-03-24 19:56 UTC, inodeman commented
jenkins retest this

2021-03-24 19:56 UTC, inodeman commented
jenkins do fdb

2021-03-24 19:59 UTC, inodeman commented
Hi @domhanak @romartin please find new artifacts here. https://drive.google.com/drive/folders/1jukaxObjhQklIDymbUC79MHZ5nk-gmwM?usp=sharing, I did tests on both BC and Kogito and tested the ability to add custom types from Data Objects, Assignments, Process and Variables and Imports. I also added more conditions coverage as requested. Thanks

2021-03-25 00:21 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDirectDiagramMarshaller.java
> +            dataTypeCache.initCache(diagramRoot);
oh sorry, you're right!! I just got confused on the package for the class.... yeah everyting ok! sorry!

2021-03-25 00:21 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
> +        if (doneLoading) {
ok I see it's replaced by an scheduler, good enought! :+1: thx

2021-03-25 00:24 UTC, romartin commented
hey @inodeman

I can't access the uploaded files you mention above, it says I need to ask for permissions... could you please make those shared file/s public?

2021-03-25 00:28 UTC, romartin commented
jenkins do fdb

2021-03-25 09:21 UTC, domhanak commented
@inodeman @romartin review results:

**VSCode:**

All Data Types options are the same in all places within one process:
-     Global, Process variables :heavy_check_mark: 
-     Assignments  :heavy_check_mark: 
-     Data Objects :heavy_check_mark: 
-     Imports :heavy_check_mark: 
-     Multiple Instance :heavy_check_mark: 

When a new custom data type is created the data type is visible on all places (datatype drop downs) within one process.  :heavy_check_mark: 

When a new custom data type is edited, the changes apply on all places within one process. :heavy_multiplication_x: 
**Current behavior:**
When you edit a custom Data Type (using the dropdown) from `Type` to `TypeRenamed` it is not changed on all places in process, instead there is a new custom variable created `TypeRenamed` and the old custom type `Type` is still available for selection.
This violates the acceptance criteria.


**Business Central**

All Data Types options are the same in all places within one process:
-     Global, Process variables :heavy_check_mark: 
-     Assignments  :heavy_check_mark: 
-     Data Objects :heavy_check_mark: 
-     Imports :heavy_check_mark: 
-     Multiple Instance :heavy_check_mark: 

When a new custom data type is created the data type is visible on all places (datatype drop downs) within one process.  :heavy_check_mark: 
However, there is a UX issue:
1.  When Adding custom type via process variables, user needs to deselect the editor (click on canvas, close properties) in order for the service to kick in. If he just creates the type in process variables and goes straight to import the type is no there yet.

When a new custom data type is edited, the changes apply on all places within one process. :heavy_multiplication_x: 
**Current behavior:**
When you edit a custom Data Type (using the dropdown) from `Type` to `TypeRenamed` it is not changed on all places in process, instead there is a new custom variable created `TypeRenamed` and the old custome type `Type` is still available for selection.
Same goes for DO created in BC using the DO editor, when renamed, the process that uses them stays the same with old names.
This violates the acceptance criteria.

Issues with types from different project are fixed.

2021-03-25 15:21 UTC, romartin commented
thanks @domhanak for the review again! 
@inodeman let's try to do some call today to see the status for this, and if it's possible to fix for tomorrow, ok? Please ping me when yo'ure around

2021-03-31 22:08 UTC, inodeman commented
jenkins retest this

2021-03-31 22:08 UTC, inodeman commented
jenkins do fdb

2021-04-21 07:10 UTC, domhanak approved these changes

2021-04-22 13:35 UTC, romartin approved these changes

2021-04-22 13:36 UTC, romartin commented
@handreyrc missing your review feedback. Thanks!

2021-04-22 19:42 UTC, merged