KOGITO-543: DMN - Read Only mode
kiegroup/kie-wb-common pull request #3361
Opened 2020-07-20 21:58 UTC by danielzhe

This PR adds the infrastructure to support read-only mode to DMN Diagrams. [See here](https://issues.redhat.com/browse/KOGITO-543).

This PR will make the DMN Editor in Chrome extension open in read only mode by default.

You can change this behavior [here](https://github.com/kiegroup/kie-wb-common/compare/master...danielzhe:KOGITO-543?expand=1#diff-83a38f27ebffb7ec7d204a1880983667R43) to make it easier to test the PR in other environments.

2020-07-21 19:34 UTC, danielzhe commented
The FDB was triggered here: https://github.com/kiegroup/kogito-tooling/issues/221#issuecomment-662063367
Let's see how it works.

2020-07-24 17:35 UTC, karreiro commented
Jenkins please retest this.

2020-07-27 20:33 UTC, danielzhe commented
Thank you, @karreiro! Changes applied!

2020-08-03 16:45 UTC, danielzhe commented
Talking with the Guilherme the Kogito guys warned that it will not be always read-only with Chrome extension. It will be another change in the future in the Kogito side that will pass a parameter to DMN specifying if the editor is on read-only mode or not. So to test it, you have to manually change it [here](https://github.com/kiegroup/kie-wb-common/pull/3361/commits/f61548de8c7f9ae42dd7278c39fca815c61f797f#diff-83a38f27ebffb7ec7d204a1880983667R43) to return true.
Ready for your review, @jomarko .

2020-08-05 12:03 UTC, karreiro commented
Jenkins please retest this.

2020-08-06 13:24 UTC, danielzhe commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/api/ReadOnlyProviderImpl.java
> +        return false;
No, because it would make the editor always be in read only mode in Chrome and we been warned from the guys from Kogito team that this is not the expected behavior.

2020-08-06 18:07 UTC, danielzhe commented
@jomarko Changes applied!

2020-08-07 04:30 UTC, jomarko commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/BaseNavigationCommandTest.java
> +        //doNothing().when(command).hidePaletteWidget(any(Boolean.class));
please remove this comment

2020-08-17 16:16 UTC, tiagobento commented
@danielzhe Hi Daniel! I'll be implementing the `read-only` feature on Kogito Tooling side, so I figured I would take a look at your PR to see how I'm going to approach that. I noticed that you created a ReadOnlyProvider class, so that you can use this flag in many places. However, as per my comment on this task's JIRA, I believe we should add that to the EditorContext, since it's an immutable property we pass to editors when they're starting up.

Do you mind please changing your PR to add the flag there? This will make the integration much easier on Kogito Tooling and also will keep the same approach that we've been doing for other similar features. Please reach out if you have question!

2020-08-18 07:14 UTC, jomarko commented
Postponing my approval due to https://github.com/kiegroup/kie-wb-common/pull/3361#issuecomment-674974508

2020-08-24 17:05 UTC, danielzhe commented
@jomarko @tiagobento Changes applied. Now we have another PR in appformer required.

2020-08-24 19:14 UTC, danielzhe commented
Jenkins run fdb

2020-08-25 12:09 UTC, jomarko requested changes
In case of readonly is true, we should:
- disable Import Data Object button [1]
- disable Include model button [2]
- ensure no exception is thrown when user open expresison of a decision node [3]

[1]
![Screenshot from 2020-08-25 14-05-56](https://user-images.githubusercontent.com/8044780/91172497-91b56800-e6dc-11ea-8bc0-32e474c0fbb5.png)

[2]
![Screenshot from 2020-08-25 14-06-11](https://user-images.githubusercontent.com/8044780/91172519-9a0da300-e6dc-11ea-8e3c-16aa2875d52c.png)


[3]
![Screenshot from 2020-08-25 14-06-39](https://user-images.githubusercontent.com/8044780/91172533-a1cd4780-e6dc-11ea-9bba-46ea7fb5f33c.png)
![Screenshot from 2020-08-25 14-06-44](https://user-images.githubusercontent.com/8044780/91172537-a5f96500-e6dc-11ea-99aa-26a049c4818a.png)

2020-08-25 21:49 UTC, danielzhe commented
@jomarko This is new. It wasn't happening before. I don't see how can this be related to the change.

2020-08-26 00:42 UTC, danielzhe commented
@jomarko Changes applied! I think the issue you reported was not caused by this PR, but I fixed on this PR to get it merged.

2020-08-26 06:59 UTC, jomarko commented
@danielzhe please push changes

2020-08-26 11:26 UTC, danielzhe commented
@jomarko Sorry. Changes pushed.

2020-08-27 13:56 UTC, jomarko approved these changes
@danielzhe thank you for your changes. 
I can confirm 'Include Model' button is disabled in readonly mode. however navigate to expression editor or import data object button still are not in appropriate state. I created a separate [jira](https://issues.redhat.com/browse/DROOLS-5605) that needs to be resolved to mark Read Only requirement as done.

2020-08-27 13:59 UTC, merged