JBPM-9266 : Stunner - Called element in Reusable sub-process is not populated
kiegroup/kie-wb-common pull request #3376
Opened 2020-07-31 20:59 UTC by inodeman

Hi @romartin @handreyrc can you review this PR? Basically every time the CalledElement for property was created and a call to get the contents it was firing up a Server event, but returned immediately so the data was not updated, if you previously selected and unselected the element it would get the right data. What I did is make the call upon the Form Provider creation so that the data is ready when the user clicked on the combo box.

2020-07-31 21:00 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-04 08:15 UTC, domhanak commented
jenkins execute full downstream build

2020-08-04 08:54 UTC, mbiarnes commented
jenkins execute full downstream build

2020-08-05 23:00 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/CalledElementFormProvider.java
> +        }.schedule(100);
looks tricky.. :) Why need for scheduling it? Can't we instead, observe to some CDI event or use some callback on the code, in order to avoid this?

2020-08-10 20:23 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-10 20:23 UTC, inodeman commented
Hi @romartin, removed Timer and instead just fired the event on PostConstruct method, works fine. Let me know

2020-08-10 20:26 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/CalledElementFormProvider.java
> +        }.schedule(100);
Hi @romartin fixed, used PostConstruct method instead

2020-08-11 09:06 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/CalledElementFormProviderTest.java
> +@RunWith(GwtMockitoTestRunner.class)
Do we need GwtMockito here? Mockito also has a spy method.

Also looks like spied object is not used later.

2020-08-12 16:14 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/CalledElementFormProviderTest.java
> +@RunWith(GwtMockitoTestRunner.class)
Hi @hasys you are right, we dont need it anymore, It was back when I used the Timer, will remove

2020-08-12 16:15 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-18 09:53 UTC, hasys commented
jenkins do fdb

2020-08-18 09:53 UTC, hasys commented
Jenkins retest this

2020-08-25 15:38 UTC, LuboTerifaj requested changes
Hello @inodeman ,

the issue is fixed only partially. There is missing process "B" from steps to reproduce in drop-down menu.

Would it be possible to add a test case for the issue?

Thank you!

2020-08-25 15:46 UTC, inodeman commented
Hi @LuboTerifaj let me check it, and yes, I will make sure to add the test case, thanks

2020-08-26 18:11 UTC, inodeman commented
jenkins do fdb

2020-08-26 18:11 UTC, inodeman commented
Jenkins retest this

2020-08-26 18:13 UTC, inodeman commented
Hi @romartin @LuboTerifaj changed it, basically when the diagram loads I am calling to populate the data for called element. @romartin can you take a look at it, I did not like where I just called the static method on Called Element to fire in BPMNSessionInitializer, maybe there is a better place to make this call. Let me know 
![image](https://user-images.githubusercontent.com/39567766/91340592-807c6200-e795-11ea-8923-5a8b5de474cd.png)

2020-08-26 18:13 UTC, inodeman commented
@LuboTerifaj reuploading artifacts, will let you know once done. Thanks

2020-08-26 20:50 UTC, inodeman commented
Hi @LuboTerifaj @romartin artifacts are here . https://drive.google.com/drive/folders/1OnZueF_zxlQswp9-jeWWlssQMRjOoNO4?usp=sharing

2020-09-01 15:34 UTC, LuboTerifaj requested changes
Hello @inodeman ,

if you delete the process A from steps to reproduce in [JBPM-9266](https://issues.redhat.com/browse/JBPM-9266) and then check the property, the process is still there. You have to deselect and then select back the reusable sub-process to reflect the changes.

Can you please also add some test cases?

Thank you!

2020-09-01 17:35 UTC, inodeman commented
Jenkins retest this

2020-09-01 17:35 UTC, inodeman commented
jenkins do fdb

2020-09-01 17:37 UTC, inodeman commented
Hi @LuboTerifaj added test case, about the new issue the reason is the service gets called when loading the diagram and when selecting the property, to fix this issue, will have to rethink the solution, if you think it is appropiate we can open a new Jira and include the issues for both Called Element and Ruleflow and this way we can merge these two PRs. Will upload artifacts shortly, let me know

2020-09-01 18:19 UTC, inodeman commented
Hi @LuboTerifaj @romartin find the latest artifacts here. https://drive.google.com/drive/folders/1OnZueF_zxlQswp9-jeWWlssQMRjOoNO4?usp=sharing

2020-09-17 09:11 UTC, LuboTerifaj commented
Jenkins execute fdb

2020-09-17 13:28 UTC, LuboTerifaj approved these changes
Hello @inodeman ,

thanks for the changes.

I have reported two issues:
- [JBPM-9362](https://issues.redhat.com/browse/JBPM-9362) Called element in Reusable sub-process is not updated after renaming
- [JBPM-9363](https://issues.redhat.com/browse/JBPM-9363) Called element and Rule flow group properties are not updated after deleting assets

Otherwise, it looks good to me.

2020-09-17 21:14 UTC, romartin approved these changes

2020-09-17 21:14 UTC, merged