JBPM-9267 : Stunner - Rule flow group is not populated
kiegroup/kie-wb-common pull request #3377
Opened 2020-07-31 21:33 UTC by inodeman

Hi @romartin @handreyrc can you review this PR? Basically the Ruleflow was not being populated because it called the server but returned results immediately before the event (back) was catched. Modified so that it initializes when the form provider gets called.

2020-07-31 21:34 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-04 14:44 UTC, inodeman commented
Jenkins execute compile downstream build

2020-08-07 08:50 UTC, LuboTerifaj commented
Hello @inodeman ,

unfortunately business-central cannot be loaded.

When I log in, "_Please wait, Loading application_" message is shown.

Master is working properly, so there must be something wrong with the war generated.

Can you please have a look at it?

Thanks!

2020-08-07 20:51 UTC, inodeman commented
Hi @LuboTerifaj just tested and rebased and I could not see an issue. Please find latest builds in https://drive.google.com/drive/folders/19CzVWmgpi7Hf7Vad5c_44c_lkJmhKUZf?usp=sharing, if continue to have the issue please the logs on the console so I can check it out, I will also retrigger builds with latest rebase

2020-08-07 20:52 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-10 19:53 UTC, inodeman commented
Hi @romartin I took out the timer, and just made a method annotated with PostConstruct and that worked fine.

2020-08-10 19:53 UTC, inodeman commented
Jenkins execute full downstream build

2020-08-12 17:05 UTC, LuboTerifaj commented
Hi @inodeman , I will check it again. Are the builds up to date here: https://drive.google.com/drive/folders/19CzVWmgpi7Hf7Vad5c_44c_lkJmhKUZf?usp=sharing ? Thanks!

2020-08-12 20:23 UTC, inodeman commented
Hi @LuboTerifaj the changes should not have effect on the builds, but just to be sure, let me re upload them. Will confirm once uploaded

2020-08-13 15:01 UTC, LuboTerifaj commented
Hello @inodeman , please do always rebuild the builds when making any changes, so I can test the latest updates that may be merged to the master. Thank you!

2020-08-13 15:05 UTC, inodeman commented
Hi @LuboTerifaj will do, yesterday could not get a build to work, had some errors in distributions, will retry today and upload if successful.

2020-08-13 20:32 UTC, inodeman commented
Hi @LuboTerifaj builds can be found here now. https://drive.google.com/drive/folders/19CzVWmgpi7Hf7Vad5c_44c_lkJmhKUZf?usp=sharing

2020-08-25 15:25 UTC, LuboTerifaj requested changes
Hello @inodeman , unfortunately the issue is still not fixed.

2020-08-25 15:46 UTC, inodeman commented
Hi @LuboTerifaj let me check it, I know I simulated it in order to develop faster and not have to build whole distributions. will check and let you know

2020-08-26 22:10 UTC, inodeman commented
Jenkins retest this

2020-08-26 22:10 UTC, inodeman commented
jenkins do fdb

2020-08-26 22:16 UTC, inodeman commented
Hi @LuboTerifaj @romartin ready for re review. I tested on distributions and it works fine now. Let me know if any issues. Uploading artifacts right now. Will let you know when done

2020-08-26 22:28 UTC, inodeman commented
Hi @LuboTerifaj @romartin artifacts can be found here . https://drive.google.com/drive/folders/19CzVWmgpi7Hf7Vad5c_44c_lkJmhKUZf?usp=sharing

2020-09-01 13:21 UTC, LuboTerifaj reviewed
Hello @inodeman ,

See my comment inline.

Can you please also add some test cases?

Otherwise it looks good to me.

Thanks!

2020-09-01 13:21 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/RuleFlowGroupFormProviderTest.java
> +@RunWith(GwtMockitoTestRunner.class)
Is this change necessary?

2020-09-01 15:46 UTC, LuboTerifaj commented
Hello @inodeman ,

In addition to my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3377#pullrequestreview-479732388), I have found an issue:
- If you delete drools file containing ruleflow group after the steps to reproduce from [JBPM-9267](https://issues.redhat.com/browse/JBPM-9267) and then check the Business Rule task's property, the ruleflow group is still there. You have to deselect and then select back the Business Rule task to reflect the changes.

Thanks!

2020-09-01 15:47 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/RuleFlowGroupFormProviderTest.java
> +@RunWith(GwtMockitoTestRunner.class)
Hi @LuboTerifaj not really when I think of it, removed

2020-09-01 15:47 UTC, inodeman commented
Hi @LuboTerifaj added test case and removed line from your comment. Uploading artifacts shortly.

2020-09-01 15:47 UTC, inodeman commented
Jenkins retest this

2020-09-01 15:47 UTC, inodeman commented
jenkins do fdb

2020-09-01 15:52 UTC, inodeman commented
> Hello @inodeman ,
> 
> In addition to my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3377#pullrequestreview-479732388), I have found an issue:
> 
> * If you delete drools file containing ruleflow group after the steps to reproduce from [JBPM-9267](https://issues.redhat.com/browse/JBPM-9267) and then check the Business Rule task's property, the ruleflow group is still there. You have to deselect and then select back the Business Rule task to reflect the changes.
> 
> Thanks!

Hi @LuboTerifaj yes, the reason is, the service gets called when the property is selected or when the diagram is loaded, same thing will apply to called element. If we want to change this, will have to do it some other way, which currently I dont know, can we open another issue to include this behaviour plus called element so that I can fix this specific issue about deleting the diagram and not having the changes reflected? that way we could merge this plus called element. Let me know what you think

2020-09-01 16:28 UTC, inodeman commented
Hi @LuboTerifaj @romartin artifacts can be found here. https://drive.google.com/drive/folders/19CzVWmgpi7Hf7Vad5c_44c_lkJmhKUZf?usp=sharing

2020-09-17 09:12 UTC, LuboTerifaj commented
Jenkins execute fdb

2020-09-17 13:57 UTC, LuboTerifaj requested changes
Hello @inodeman ,

there are still a few issues. At least the first one should be resolved:
 - If **a new rule flow group** is created, the change **is not reflected in** Business rule task's **property**.
   - To reproduce the issue just go through steps to reproduce in jira, then add another rule file and open Rule flow Group property again. 
 - If you edit or delete rule file containing ruleflow group, the changes are not reflected in Business rule task.
   - Regarding the deleting a rule file, I have already reported the issue here: [JBPM-9363](https://issues.redhat.com/browse/JBPM-9363) Called element and Rule flow group properties are not updated after deleting assets
  - Regarding the editing we can report in separate jira if it's not easy to fix it in this PR. Please let me know what do you prefer. 

Thank you!

2020-09-17 15:19 UTC, inodeman commented
Hi @LuboTerifaj, just talked to @romartin about how to fix this. He mentions that also Service Tasks behave this way, they do not update dynamically, only on diagram reload. He recommended we put it as an improvement. Let me know what you think, I am looking also for ways to fix it.

2020-09-22 13:14 UTC, LuboTerifaj approved these changes
Hi @inodeman , @romartin ,

I see. Here are reported issues:

- [JBPM-9372](https://issues.redhat.com/browse/JBPM-9372) Stunner - A new Rule flow group is not reflected in Business rule task's property 
- [JBPM-9373](https://issues.redhat.com/browse/JBPM-9373) Stunner - Edited Rule flow group is not reflected in Business rule task's property

Once the PR is rebased with master, it should be ready for merging.

Thank you!

2020-09-22 13:35 UTC, inodeman commented
Jenkins retest this

2020-09-22 13:35 UTC, inodeman commented
Jenkins execute fdb

2020-09-22 13:35 UTC, inodeman commented
Great!, Thanks a lot @LuboTerifaj

2020-09-22 14:08 UTC, romartin commented
Please lemme know @inodeman when this is ready to merge. 
Thx guys!

2020-09-22 14:10 UTC, inodeman commented
HI @LuboTerifaj @romartin , artifact uploaded here . https://drive.google.com/drive/folders/19CzVWmgpi7Hf7Vad5c_44c_lkJmhKUZf?usp=sharing

2020-09-22 14:10 UTC, inodeman commented
Hi @romartin ready for merge :-)

2020-09-22 14:12 UTC, romartin commented
it is not @inodeman ! we need green builds for merging... lemme once completed properly

2020-09-22 21:02 UTC, romartin commented
Hey @inodeman , the FDB failed, could you please check if something is wrong? (urgent plz)

2020-09-22 21:08 UTC, romartin commented
merging as CI failures are just a few tests failed, which are not realted to this work.

2020-09-22 21:08 UTC, merged