AF-2542: GWT 2.9 upgrade
kiegroup/kie-wb-common pull request #3395
Opened 2020-08-20 00:30 UTC by porcelli

**JIRA**: [AF-2542](https://issues.redhat.com/browse/AF-2542)

**referenced Pull Requests**: 

* https://github.com/kiegroup/lienzo-core/pull/122
* https://github.com/kiegroup/lienzo-tests/pull/103
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1442

2020-08-20 00:37 UTC, porcelli commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/factory/BPMNGraphFactoryImpl.java
> +        final Index index = (Index) indexBuilder.build(graph);
the new version of JDT that GWT has a hard time to resolve some generics, thus the need to the `unnecessary` cast

2020-08-20 00:37 UTC, porcelli commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/src/main/java/org/kie/workbench/common/stunner/cm/factory/CaseManagementGraphFactoryImpl.java
> +        return new DirectGraphCommandExecutionContext(definitionManager, factoryManager, (Index<?,?>) indexBuilder.build(graph));
the new version of JDT that GWT has a hard time to resolve some generics, thus the need to the `unnecessary` cast

2020-08-20 08:24 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/factory/BPMNGraphFactoryImpl.java
> +        final Index index = (Index) indexBuilder.build(graph);
I think it is good to add a comment to the code to prevent clean up suggested by Sonar Cloud

2020-08-20 08:24 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/src/main/java/org/kie/workbench/common/stunner/cm/factory/CaseManagementGraphFactoryImpl.java
> +        return new DirectGraphCommandExecutionContext(definitionManager, factoryManager, (Index<?,?>) indexBuilder.build(graph));
I think it is good to add a comment to the code to prevent clean up suggested by Sonar Cloud

2020-08-20 09:04 UTC, hasys requested changes
Hi @porcelli, the build is failing, see inline comments for more details. Thank you!

2020-08-20 09:04 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/util/PrintHelper.java
> -            return true;
This change causing build error:

```
03:10:17  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-wb-common-stunner-client-common: Compilation failure
03:10:17  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/new-PR-kie-wb-common-master.pullrequests/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/util/PrintHelper.java:[85,37] incompatible types: bad return type in lambda expression
03:10:17  [ERROR]     missing return value
03:10:17  [ERROR] -> [Help 1]
03:10:17  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-wb-common-stunner-client-common: Compilation failure
03:10:17  /home/jenkins/workspace/KIE/master/pullrequest/new-PR-kie-wb-common-master.pullrequests/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/util/PrintHelper.java:[85,37] incompatible types: bad return type in lambda expression
03:10:17      missing return value
03:10:17  
```

2020-08-24 16:40 UTC, porcelli commented
Jenkins do fdb

2020-08-25 06:38 UTC, mareknovotny commented
@porcelli here doesn't make sense to launch FDB, only on top level PR set, so on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1442 ;)

2020-08-25 08:00 UTC, mareknovotny commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/util/PrintHelper.java
> -            return true;
@porcelli the upgrade was taken, not maybe here, but in FDB on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1442
Looking into https://repository.jboss.org/nexus/index.html#nexus-search;gav~org.apache.sshd~~2.0.0~~ the package for Command class is wrong, it should be `org.apache.sshd.server.command.Command` not the `org.apache.sshd.server.Command` and i guess it is the same for second occurrence too

2020-08-25 10:13 UTC, Ginxo commented
@porcelli @hasys this PR https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/100 is pending to be merged in order to allow Jenkins FDB to work

2020-08-25 10:45 UTC, Ginxo commented
Jenkins do fdb

2020-08-25 13:43 UTC, mbiarnes commented
Jenkins do fdb

2020-08-26 04:03 UTC, Srihari1192 commented
Jenkins run fdb

2020-08-27 07:44 UTC, mbiarnes commented
Jenkins run fdb

2020-08-27 07:44 UTC, mbiarnes commented
Jenkins retest this

2020-08-27 12:05 UTC, mbiarnes commented
Jenkins retest this

2020-08-27 14:40 UTC, mbiarnes commented
Test comment

2020-08-28 07:23 UTC, mbiarnes commented
FDB test comment

2020-08-28 09:40 UTC, mbiarnes commented
FDB test comment

2020-08-28 10:28 UTC, mbiarnes commented
FDB test comment

2020-09-16 13:30 UTC, mareknovotny commented
Jenkins retest this

2020-10-19 06:39 UTC, mareknovotny commented
closing in favor of https://github.com/kiegroup/kie-wb-common/pull/3446

2020-10-19 06:39 UTC, closed without merging