KOGITO-3364: [DMN Designer] Multiple DRDs support - When a node is deleted in the DRG, undo/redo operations do not work properly
kiegroup/kie-wb-common pull request #3447
Opened 2020-10-01 21:25 UTC by danielzhe

**JIRA**: [KOGITO-3364](https://issues.redhat.com/browse/KOGITO-3364)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2020-10-05 13:57 UTC, danielzhe commented
Working on SonarCloud...

2020-10-05 18:55 UTC, danielzhe commented
jenkins do fdb

2020-10-06 13:19 UTC, karreiro commented
Jenkins do fdb.

2020-10-06 13:43 UTC, karreiro approved these changes
Great stuff, @danielzhe LGTM and works fine!

I've left just a non-blocking comment ;-)

2020-10-06 13:43 UTC, karreiro commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNCanvasHandler.java
> +
Can we remove these extra lines? :-)

2020-10-06 20:06 UTC, danielzhe commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNCanvasHandler.java
> +
Removed! Thank you, @karreiro !

2020-10-06 20:25 UTC, karreiro approved these changes

2020-10-12 09:24 UTC, jstastny-cz requested changes
Please respond to the Sonar check issues introduced by this PR.

2020-10-12 09:24 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommand.java
> +    public Node<? extends View<?>, Edge> getSourceNode(final GraphCommandExecutionContext context) {
sonar reporting critical code smells when having generic wildcards in return types: https://sonarcloud.io/organizations/kiegroup/rules?open=java%3AS1452&rule_key=java%3AS1452

2020-10-12 09:24 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommand.java
> +        if (getDiagramId().isPresent()) {
here sonar reports bug on not calling isPresent() before get() on optional ... and the reason IMO is, that it's not called on a variable (method returns new optional each time). Please introduce a variable.

2020-10-12 09:24 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionTargetNodeCommand.java
> +        if (getDiagramId().isPresent()) {
again, please introduce variable.

2020-10-12 09:26 UTC, jstastny-cz commented
jenkins do fdb

2020-10-15 14:34 UTC, danielzhe commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommand.java
> +    public Node<? extends View<?>, Edge> getSourceNode(final GraphCommandExecutionContext context) {
The problem here is that I'm just returning something from the super class. I think that to fix that we would need to do a big refactor in other classes not involved in this PR.

2020-10-15 14:48 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommand.java
> +    public Node<? extends View<?>, Edge> getSourceNode(final GraphCommandExecutionContext context) {
I thought so, just wanted to clarify. IMO this should not block this PR.

2020-10-15 18:11 UTC, danielzhe commented
Changes applied, @jstastny-cz! Thank you!

2020-10-15 18:11 UTC, danielzhe commented
jenkins do fdb

2020-10-20 13:47 UTC, danielzhe commented
@jstastny-cz Ready for your review. Thank you! =)

2020-10-22 10:52 UTC, jstastny-cz approved these changes
LGTM, verified using the FDB BC war.

2020-10-22 13:32 UTC, merged