Kogito 3517
kiegroup/kie-wb-common pull request #3454
Opened 2020-10-15 20:24 UTC by handreyrc

Hey @romartin: Please, could you review this PR?

**JIRA**: [KOGITO-3517](https://issues.redhat.com/browse/KOGITO-3517)
**JIRA**: [RHPAM-3197](https://issues.redhat.com/browse/RHPAM-3197)

**Referenced Pull Requests**:
* [kogito-tooling](https://github.com/kiegroup/kogito-tooling/pull/290)

**VS Code**: [plugin](https://drive.google.com/file/d/1DnnlIF-z3NaTLSHxnDG_W67t5hqWOX-s/view?usp=sharing)

Thanks!

2020-10-15 20:29 UTC, handreyrc commented
Jenkins run fdb

2020-10-19 03:06 UTC, handreyrc commented
Jenkins run fdb

2020-10-21 13:29 UTC, romartin approved these changes
Looks good to me @handreyrc ! Thanks!

2020-10-21 13:30 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImpl.java
> +            e.stopPropagation();
oh nice , so that finally works for not propagating the events to the parent window right? :)

2020-10-21 13:31 UTC, tiagobento approved these changes

2020-10-21 15:53 UTC, handreyrc commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImpl.java
> +            e.stopPropagation();
Yep it works fine@romartin! 
I thought in a first look it could mess up with keyup and keypress events, but we have different concepts here. Stopping event propagation just prevent it to go up in the elements hierarchy, but doesn't prevent events to be commited at that level.  The preventDefault does that.

2020-10-21 21:17 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImpl.java
> +            e.stopPropagation();
true! and nice job, thanks! :+1:

2020-10-22 10:59 UTC, domhanak approved these changes
Looks good to me. 
Tested with VSCode 1.50.1.
I was able to open shortcuts panel using `shift+/` or `shift+?` and the panel was not opening while I was renaming node name.
Verified in BPMN, DMN, I was not able to test in SCESIM.

2020-10-22 11:01 UTC, domhanak requested changes
Checking the business central...

2020-10-22 20:14 UTC, romartin commented
good point @domhanak , plz check BC and let us know if it works properly as with kogito... :+1: 
Thanks!!

2020-10-26 07:29 UTC, domhanak reviewed
Looks good from business central point of view.

I was unable to reproduce RHPAM-3197 with these changes.

@handreyrc I noticed a small delay when opening the text editor of node.
What I did:
1. Open node name editor and click on canvas
2. Repeat for other nodes in process.
After 2-3 nodes the text editor for name takes some time to fully show. There is 2-3 seconds.
Could you please let me know if this is related?

2020-10-26 07:49 UTC, domhanak approved these changes
@handreyrc  I checked master and the delay when triggering the node name editor is present there also.
Approved.

2020-10-26 12:24 UTC, merged

2020-10-26 14:56 UTC, romartin commented
@domhanak I noticed some delay when starting the inline edition for a node, but looks it's just due to the backgrand animation itself, and do not prevent from early typing. Is that correct? maybe you don't like the animation guys?