DROOLS-5749: [DMN Designer] Multiple DRDs support - When users open a DMN with duplicated information requirements, the marshaller doesn't fix it
kiegroup/kie-wb-common pull request #3462
Opened 2020-10-22 03:35 UTC by karreiro

**JIRA**: [DROOLS-5749](https://issues.redhat.com/browse/DROOLS-5749) - [DMN Designer] Multiple DRDs support - When users open a DMN with duplicated information requirements, the marshaller doesn't fix it

**Business Central**: [WAR file](https://www.dropbox.com/s/toe10dnah6sgduw/business-central-DROOLS-5749.war?dl=0)
**VS Code**: [plugin](https://www.dropbox.com/s/4auffyl3phrvvlb/vscode-plugin-DROOLS-5749.vsix?dl=0)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2020-10-22 03:39 UTC, karreiro commented
Jenkins do fdb.

2020-10-22 09:18 UTC, jstastny-cz requested changes

2020-10-22 09:18 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
> +    private <T extends JSITDMNElement> List<T> distinct(final List<T> list) {
Could we add here second argument and combine the lists like:
```
private <T extends JSITDMNElement> List<T> distinct(final List<T> list, final List<T> secondList) {
    List<T> toBeProcessed = new ArrayList(list);
    list.addAll(secondList);
    // the rest is the same, just process the combined list
    final Map<String, T> map = new HashMap<>();
    forEach(toBeProcessed, item -> {
        map.putIfAbsent(item.getId(), Js.uncheckedCast(item));
    });
    return new ArrayList<>(map.values());
}
```
The usage then wouldn't need to first to invoke `addAllAuthorityRequirement` and then retrospectively filtering and setting using `setAuthorityRequirement`.
Resulting in a single call for each requirement type
```
existingKnowledgeSource.setAuthorityRequirement(
    distinct(
        existingKnowledgeSource.getAuthorityRequirement(),
        nodeKnowledgeSource.getAuthorityRequirement()
    )
);
```
which is IMO nicer than
```
existingKnowledgeSource.addAllAuthorityRequirement(nodeKnowledgeSource.getAuthorityRequirement().toArray(new JSITAuthorityRequirement[0]));
existingKnowledgeSource.setAuthorityRequirement(distinct(existingKnowledgeSource.getAuthorityRequirement()));
```

2020-10-22 12:41 UTC, karreiro commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
> +    private <T extends JSITDMNElement> List<T> distinct(final List<T> list) {
Nice enhancement. Thanks, @jstastny-cz!

2020-10-22 12:41 UTC, karreiro commented
Thanks @jstastny-cz. Changes applied on new commit :-)

2020-10-22 13:12 UTC, danielzhe approved these changes

2020-10-22 13:52 UTC, jstastny-cz commented
jenkins do fdb

2020-11-03 14:50 UTC, jstastny-cz approved these changes
LGTM

2020-11-03 14:51 UTC, merged