KOGITO-2693: Embeddable editors (Milestone 1)
kiegroup/kie-wb-common pull request #3464
Opened 2020-10-22 19:33 UTC by paulovmr

**Thank you for submitting this pull request**

**JIRA**: [KOGITO-2693](https://issues.redhat.com/browse/KOGITO-2693)

**Referenced Pull Requests**:
* 

**Business Central**: [WAR file](https://drive.google.com/file/d/1ty-j7N1m-Pg0Yxjoririy6jJ4ug-URX0/view?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2020-10-22 19:38 UTC, paulovmr commented
Jenkins run fdb

2020-11-03 12:41 UTC, jstastny-cz requested changes

2020-11-03 12:41 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorDOMElementTest.java
> -    @Test
where is the equivalent of this test? Cause the functionality from `onMonacoLoaded` method now is moved (but retained) into `setupInternalComponent` method - we should not throw away test coverage.

2020-11-04 18:20 UTC, paulovmr commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorDOMElementTest.java
> -    @Test
I've now moved the checks to the `setupInternalComponent` test.

2020-11-04 18:20 UTC, paulovmr commented
Jenkins run fdb

2020-11-04 19:54 UTC, paulovmr commented
Jenkins run fdb

2020-11-10 21:33 UTC, karreiro reviewed
Excellent work, @paulovmr. Clever approach with `appformer-js-monaco` ;-)

I've left only a minor comment on this PR. Please, let me know wdyt!

Thank you :-)

2020-11-11 07:42 UTC, jstastny-cz commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorDOMElementTest.java
> -    @Test
Thanks

2020-11-11 07:42 UTC, jstastny-cz approved these changes

2020-11-12 15:30 UTC, jstastny-cz commented
I've run our regression suite with the BC war from FDB, no issues found.

2020-11-12 15:34 UTC, karreiro approved these changes
Thank you, @paulovmr.

2020-11-12 15:37 UTC, vpellegrino approved these changes
LGTM, good work @paulovmr

2020-11-16 12:20 UTC, tiagobento approved these changes

2020-11-16 15:20 UTC, paulovmr commented
Jenkins run fdb

2020-11-17 13:17 UTC, paulovmr commented
Jenkins run fdb

2020-11-17 16:53 UTC, paulovmr commented
Jenkins run fdb

2020-11-17 18:58 UTC, paulovmr commented
Jenkins run fdb

2020-11-18 02:06 UTC, karreiro commented
Jenkins run fdb.

2020-11-18 12:14 UTC, karreiro commented
Jenkins run fdb.

2020-11-18 13:37 UTC, paulovmr commented
Jenkins run fdb

2020-11-18 14:03 UTC, paulovmr commented
Jenkins run fdb

2020-11-18 17:55 UTC, paulovmr commented
Jenkins run fdb

2020-11-19 03:05 UTC, paulovmr commented
Jenkins run fdb

2020-11-19 15:58 UTC, paulovmr commented
Jenkins run fdb

2020-11-19 18:33 UTC, paulovmr commented
Jenkins run fdb

2020-11-19 19:12 UTC, paulovmr commented
Jenkins run fdb

2020-11-20 18:33 UTC, merged