[DROOLS-5783] Make droolsjbpm-integration repo independent from appformer
kiegroup/kie-wb-common pull request #3472
Opened 2020-11-03 15:29 UTC by danielezonca

https://issues.redhat.com/browse/DROOLS-5783

Description:
The goal of this PR is to cleanup `droolsjbpm-integration` repo from unnecessary relation with other repos (in this case `appformer`). It is a sort of followup of this PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1505 that tries to do the same but it has been partially reverted because of some remaining usages

Details of this part of the PR:
- moving `kie-identity-session-provider` from `droolsjbpm-integration` repo to here because it is used by some -wb repos but it uses kie-internal so this is the first repo in common we can use

NOTE: I preserved same group and artifact of `kie-identity-session-provider` to preserve downstream usages. If we don't like to have a different naming I can change it + all downstreaming repos

@mareknovotny @Ginxo @lucamolteni @mariofusco @ederign 

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2020-11-03 15:47 UTC, lucamolteni approved these changes

2020-11-03 17:36 UTC, adrielparedes approved these changes

2020-11-04 06:44 UTC, mareknovotny commented
@danielezonca there are few sonarcloud failures we could fix and have better source code. I know you are not the author of the code, but I think this is simple to fix now. WDYT?

2020-11-04 06:47 UTC, mareknovotny commented on kie-identity-session-provider/src/main/java/org/kie/provider/impl/SafeIdentityProvider.java
> +import javax.enterprise.context.RequestScoped;
not used anywhere?
```suggestion

```

2020-11-04 06:49 UTC, mareknovotny commented on kie-identity-session-provider/src/main/java/org/kie/provider/impl/SafeIdentityProvider.java
> +        List<String> roles = new ArrayList<String>();
just minor thing, but sonar will be happy?
```suggestion
        List<String> roles = new ArrayList<>();
```

2020-11-04 06:50 UTC, mareknovotny commented on kie-identity-session-provider/src/main/java/org/kie/provider/impl/SafeSessionInfoProvider.java
> +    private static final Logger logger = LoggerFactory.getLogger( SafeIdentityProvider.class );
A copy&paste error from past I think 

```suggestion
    private static final Logger logger = LoggerFactory.getLogger( SafeSessionInfoProvider.class );
```

2020-11-04 06:51 UTC, mareknovotny commented on kie-identity-session-provider/src/main/java/org/kie/provider/impl/SafeSessionInfoProvider.java
> +        List<Role> roles = new ArrayList<Role>(roleStrList.size());
shorter version

```suggestion
        List<Role> roles = new ArrayList<>(roleStrList.size());
```

2020-11-04 06:53 UTC, mareknovotny requested changes
Suggested some problems from original moved source code, You can simply accept it to reduce sonarcloud failures.

2020-11-04 08:10 UTC, danielezonca commented
@mareknovotny 
Thanks for the suggestions, accepted :+1:

2020-11-04 08:19 UTC, mariofusco approved these changes

2020-11-04 11:12 UTC, mareknovotny approved these changes

2020-11-09 08:34 UTC, merged