KOGITO-3891 & KOGITO-540: Editors refactoring & BPMN editor readonly
kiegroup/kie-wb-common pull request #3498
Opened 2020-11-23 00:55 UTC by romartin

See:

- Editors refactoring at https://issues.redhat.com/browse/KOGITO-3891
- BPMN editor readonly support at https://issues.redhat.com/browse/KOGITO-540

It **DEPENDS ON**:

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1537

Thanks!

2020-11-24 11:26 UTC, domhanak commented on kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
> +public class DMNDiagramEditorTest {
TODO, putting a comment here so we do not forget about these tests

2020-11-24 11:28 UTC, domhanak commented on kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommandsTest.java
> +public class DMNEditorSessionCommandsTest /*extends EditorSessionCommandsTest {
same as above

2020-11-24 11:37 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/editor/StunnerEditor.java
> +public class StunnerEditor {
Could we have a javadoc for this class?

2020-11-24 11:47 UTC, domhanak commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/editor/StunnerEditorTest.java
> +public class StunnerEditorTest {
Does it make sense to add some cases where opening ends in failure? For example`testOpenFailure()` ?

2020-11-24 23:41 UTC, romartin commented
Hey @domhanak 

Thanks for early looking at this! 

Code on this PR is almost ready, just missing a few commented-out test cases and TODO's, but do not yet spend much time on testing this stuff in runtime please, as I'm not still sure everythning works as before. I'm just bulding everything locally and trying to fix a couple of bugs I've already identified.

You can continue with the code review, but please appreciate if you can hold the testing on this PR for a few days, I'll let you know once I'm happy enough for starting to test this.

Also, I think would be fine if we can just meet a few minutes to talk about this PR - once I can explain the idea behind these changes I think will help you on the code review, also on what to really test (again) on the runtime side. 

Let's sync tomorrow and let's move this forward, thanks! :+1:

2020-11-27 22:38 UTC, romartin commented
jenkins do fdb

2020-11-27 22:40 UTC, romartin commented
Hey @domhanak 

I've been testing and doing latest fixes, also rebased from master. I'm only missing to complete a few test cases, nothing hard :)

Soo this is **ready for review** again!! Feel free to start testing both BC and kogito editors, for both BPMN and DMN, and lemme know if somethign got broken. Also this inclues ready-only mode, so feel free to do some tests on ready only as well.

Thanks in advance!

2020-12-01 00:59 UTC, romartin commented
jenkins do fdb

2020-12-07 14:46 UTC, domhanak commented
jenkins retest this

2021-01-05 10:45 UTC, domhanak commented
@romartin  I am building a fresh war, hopefully the my master rebase is correct. Could you please rebase and get the builds green? I still notice some TODO's in the code, let me know when resolved I do another round of tests. Earlier war was working well I didn't see anything suspicious. I will try with new one with master changes

2021-01-12 09:09 UTC, domhanak commented
Looks good so far no issues that I caught, @romartin could you please upload vsix with readonly mode enabled?

2021-01-22 23:56 UTC, romartin commented
jenkins do fdb

2021-01-26 00:46 UTC, romartin commented
Jenkins do fdb

2021-01-26 00:52 UTC, romartin commented
Hey @domhanak @caponetto 

Would appreciate your review on the UI side, although there are still missing some TODOs to complete, which I'm already working on that. Anyway those do not prevent from testing this stuff. 

This PR is not really introducing new features, but it contains some considerable refactoring on the common parts that may affect any both BPMN and DMN editors, also in both BC and Kogito spaces.

So please, early feedback will be appreciated. this stuff needs to be merged asap, I'll just do cleanps and fix tests during the following days, let's keep in touch!!

Thanks!ç
CC  @ederign @karreiro

2021-01-26 18:46 UTC, caponetto reviewed
Hi @romartin, thanks for the PR!
I'm not so familiar with the core code of the editors but I can see lots of improvements.
The code looks less complex and more organized for sure!
I saw many `TODOs` but I understand you are working on them, right?
Could you please share a `war` file (bc) and a `vsix` file with these changes included for us to test?

2021-01-26 22:09 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/resources/org/kie/workbench/common/stunner/kogito/StunnerKogitoClient.gwt.xml
> +  ~ Copyright 2019 Red Hat, Inc. and/or its affiliates. c
oops, good catch! fixing. thanks!

2021-01-27 02:04 UTC, romartin commented
Hey @domhanak @caponetto 

Thanks for your collaboration. Yeah I'm just missing to complete a few unit tests and some TODOs but it should not affect the UI testing, it's just the unit testing and clean ups. Will try to have this stuff done by tomorrow.

Anyway, please feel free to move forward with the testing both `BPMN / DMN`, in both `Kogito / BC` spaces. 
Here are the artifacts for testing:
- The VSIX (authoring mode) -> https://drive.google.com/file/d/1u7u_Ptw7WOPkTDQgXURXr9LQ6RbfBgcn/view?usp=sharing
- The VSIX (read only mode) -> https://drive.google.com/file/d/1hDw41bSD73vFFiOnkyQc1whNopMGqvW0/view?usp=sharing
- The Business Central artifacts will be generated by the CI builds (I just tested the generated builds and are working)

Thanks!
Roger

2021-01-27 02:06 UTC, romartin commented
jenkins do fdb

2021-01-27 14:36 UTC, caponetto commented
Hi @romartin, let me share some feedback about the `vsix` files.

Read-only mode is working fine for `bpmn` and `dmn` files.
However, I've observed that I was able to do two "add" operations in `bpmn` files, though I couldn't save it:
1. Process Data -> Process Variables -> I was able to add tags.
1. Process -> Imports -> I was able to add data type imports.

I don't know if this is expected but I'd personally expect everything blocked.
Anyway, it is not a big deal, it is just FYI. :)

Question: Should read-only mode work for `scesim` files as well? I can do some edits here.

Regarding the regular kogito editors, i.e. not in read-only mode:
I've observed a minor bug, but I confirmed that it is also occurring on master.
Please see in the gif below that the points in the canvas are being duplicated.
![canvas_refs](https://user-images.githubusercontent.com/638737/106004895-6f13ea80-6092-11eb-9020-4e80a57e8605.gif)

Lastly, I've observed that the state control is not working properly.
For example, if I make 3 changes and do an `UNDO` operation 3 times, then only the last edit is undone.
Have you seen that?

I'll continue with the tests and let you know if I find anything new.
Please let me know if you have any questions.

2021-01-27 19:47 UTC, caponetto commented
@romartin
I've found this issue while testing the `war` file:

![bc_issue](https://user-images.githubusercontent.com/638737/106044929-232b6a80-60bf-11eb-9efd-09ebcebb7d5d.gif)

2021-01-27 20:57 UTC, romartin commented
thanks guys for your feedback! good catches!

Even if some issue is already reproduce on master, let's at least try to report everything we found here. At the end I can try to fix as much as possible, although as this PR is quite big and we're really instered on having the readonly mode, let's also be pragmatic and try not making the scope for it too big.

So please go ahead and continue with your tests. I'm going to check all your comments  (will also provide feedback later), and try to cleanup all TODOs, so let's keep in touch!

Thanks again!

2021-01-27 21:17 UTC, romartin commented
BTW @caponetto good Q about scesim, I'm not really sure if it supports ready mode. Do you know @karreiro ? Anyway I don't think this PR should affect scesim, it's a different module.

2021-01-28 16:12 UTC, caponetto commented
@romartin
Another issue that I've found:

![Peek 2021-01-28 13-09](https://user-images.githubusercontent.com/638737/106165792-39423500-616a-11eb-817e-7496b380f4de.gif)

2021-01-28 16:37 UTC, romartin commented
thanks  @caponetto 

I'm just working on some of ithe issues repored and hopefully between today/tomorrow I'll try to have everything ready. I'm also writting down all these issues you reported, so if there are some that finally get postponed, we'll be able to report those.

Thanks again for the review work, appreciated!

2021-01-29 11:23 UTC, karreiro reviewed
Thank you, @romartin. It's great to refactor and remove some lines of code! However, I've noticed some issues I'd like to share:

- The data types shortcuts are not working anymore, so users cannot use arrows to navigate between types, save, or start the edit mode (it works in the dev web app, but doesn't work on BC):
![data-types](https://user-images.githubusercontent.com/1079279/106269126-63f4c200-622c-11eb-9ef7-69857f30838c.gif)

- The multiple DRDs support doesn't work anymore (@danielzhe, could you please review this PR, and give us some clues about why it's not working?):
![multiple-drds-issue](https://user-images.githubusercontent.com/1079279/106269153-6bb46680-622c-11eb-8c6b-d5377612b534.gif)

2021-02-01 14:15 UTC, romartin commented
thanks @karreiro for the review too!
I'm working on the fixes you mention, will let you know :+1:

2021-02-03 00:37 UTC, romartin commented
jenkins do fdb

2021-02-04 18:38 UTC, danielzhe commented
@romartin @karreiro I tried to run the .war but had no idea. I think I have to run it local, but it have conflicts now. Just waiting for the conflicts to be fixed to run it local.

2021-02-05 12:38 UTC, romartin commented
thanks @danielzhe - I'll rebase and let you know once ready :+1:

2021-02-09 22:53 UTC, romartin commented
jenkins do fdb

2021-02-09 22:54 UTC, romartin commented
@danielzhe @karreiro rebased! Although same issue on DMN -> DRD... will keep trying, let's keep in touch. 
Thanks!

2021-02-15 23:48 UTC, danielzhe commented
@romartin @karreiro Is the issue with DRDs fixed? I was trying to reproduce it to help to fix it but it seems that is working now, if I'm not wrong.

2021-02-16 18:16 UTC, karreiro commented
It's working indeed, @danielzhe!

@romartin I will perform some extra checks.. but something I've already noticed is that the "Documentation" tab seems to not be working (but I tested the development webapp only). As soon as I finish the tests I will leave a message here 🚀

2021-02-16 22:41 UTC, romartin commented
oh nice @karreiro @danielzhe ! I'm also now working on rebasing this again and doing last checks, let's see if we can merge ti ASAP...
Thanks for your collaboaration, really appreciated!

2021-02-18 16:20 UTC, karreiro reviewed
Thank you for the updates, @romartin! :-)

Things work fine on **kie-wb-common-dmn-webapp-standalone**, however I just built the VSCode plugin (**kie-wb-common-dmn-webapp-kogito-runtime**).. and I notice that:
- users cannot save the model
- users cannot create a DRD (probably @danielzhe will be able help with this one)

![2021-02-18 17 04 24](https://user-images.githubusercontent.com/1079279/108385745-43f16680-720c-11eb-82fd-a0bab23852eb.gif)

I'm including @jomarko on the ensemble, so he we can have extra eyes checking DMN corner cases :-)

Finally.. @romartin could you please rebase the ensemble with master? Then, @danielzhe @jomarko will be able to proper build artifacts locally :-)

Thanks, @romartin 🚀

2021-02-22 08:50 UTC, domhanak commented
@romartin Hello Roger! What is the current status of this PR? Could you please rebase, provide war, vsix and get the build green? Everytime I want to do the review, there are conflicts, builds are red and there is no war or vsix shared.
Also, I see review requests from 
@caponetto @danielzhe @jomarko @karreiro  but none of them approved yet.

@romartin As I mentioned earlier, haveing 2 PR's one with refactoring and one with read-only mode would make things faster.

2021-02-23 21:39 UTC, jomarko commented
Jenkins do fdb

2021-03-01 15:47 UTC, jomarko commented
@romartin hello, there are two failing tests https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-master.pr/630/, one of them indicates palin text editor was not opened for and 'broken' dmn asset,. I noticed some discussion in 'Drools Tools' google chat room, however my understanding was that it is not a part of this PR. could you please confirm if ace/plain text editor should be affected somehow by this PR?

2021-03-01 22:31 UTC, jomarko requested changes
@romartin thank you for the PR. It is good to see a clean up after long time. however the amount of changed files makes me trouble to review code comprehensively. I focused on manual checking. Here are my findings.

### 01
VS Code extension

Once a DRD is created
![Screenshot from 2021-03-01 22-10-24](https://user-images.githubusercontent.com/8044780/109559543-185b5f80-7adb-11eb-99ec-cc345a4e7c5a.png)

Editors remains empty
![Screenshot from 2021-03-01 22-10-30](https://user-images.githubusercontent.com/8044780/109559587-2610e500-7adb-11eb-93f2-26035b8468eb.png)

In business central error dialogue is shown
```
Uncaught exception: Exception caught: CDI Event exception: CommandType=CDIEvent, BeanType=org.kie.workbench.common.stunner.core.client.canvas.event.registration.CanvasElementAddedEvent, BeanReference=org.kie.workbench.common.stunner.core.client.canvas.event.registration.CanvasElementAddedEvent@104b4, FromClient=1 sent to [unavailable] Caused by: CDI Event exception: CommandType=CDIEvent, BeanType=org.kie.workbench.common.stunner.core.client.canvas.event.registration.CanvasElementAddedEvent, BeanReference=org.kie.workbench.common.stunner.core.client.canvas.event.registration.CanvasElementAddedEvent@104b4, FromClient=1 sent to [unavailable] Caused by: DMN Diagram root could not be found.
```
### 02
Business central

As I saw we touched some `ReadOnly` related classes, I tried to open DMN in read only mode(opening some older commit in version history)
![Screenshot from 2021-03-01 22-47-45](https://user-images.githubusercontent.com/8044780/109563677-6161e280-7ae0-11eb-9869-66a49c54f1c1.png)


Then when I tried to view expression editor of a decision node, I got an exception
![Screenshot from 2021-03-01 22-47-56](https://user-images.githubusercontent.com/8044780/109563719-73dc1c00-7ae0-11eb-8338-0d7dcf27bd6e.png)

Are we sure this is not caused by changes in this PR? In Chrome extension kogito channel the same scenario worked fine - there we open all DMN assets in read only mode by default.

### 03
Business central

Is Dirty indicator is still present after DMN is saved.
![Screenshot from 2021-03-01 23-02-12](https://user-images.githubusercontent.com/8044780/109565088-42fce680-7ae2-11eb-95a1-9829a55bbc82.png)

### 04
Business central

If the same DMN file is opened second time, the undo/redo buttons are always disabled
1. open a project
2. create **a.dmn** file
3. Add a decision node inside - notice undo button is enabled
4. save and reopen the **a.dmn** file
5. Drag the decision node - notice undo button is disabled 

### 05
Business central

Opening an invalid dmn file throws an error dialogue instead of opening plain text editor
```
{"ToSubject":"org.kie.workbench.common.dmn.api.DMNContentService:RPC.getProjectContent:org.uberfire.backend.vfs.Path:java.lang.String::748:RespondTo:RPC"} | Uncaught exception: Client-side exception occurred although RPC call succeeded. Caused by: Exception caught: Exception caught: CDI Event exception: CommandType=CDIEvent, BeanType=org.uberfire.client.views.pfly.multipage.MultiPageEditorSelectedPageEvent, BeanReference=org.uberfire.client.views.pfly.multipage.MultiPageEditorSelectedPageEvent@2cfc1, FromClient=1 sent to [unavailable] Caused by: Exception caught: CDI Event exception: CommandType=CDIEvent, BeanType=org.uberfire.client.views.pfly.multipage.MultiPageEditorSelectedPageEvent, BeanReference=org.uberfire.client.views.pfly.multipage.MultiPageEditorSelectedPageEvent@2cfc1, FromClient=1 sent to [unavailable] Caused by: CDI Event exception: CommandType=CDIEvent, BeanType=org.uberfire.client.views.pfly.multipage.MultiPageEditorSelectedPageEvent, BeanReference=org.uberfire.client.views.pfly.multipage.MultiPageEditorSelectedPageEvent@2cfc1, FromClient=1 sent to [unavailable] Caused by: (TypeError) : Cannot read property 'weq' of undefined
```

We should address all points 01 - 05, but 02 (that is maybe not so serious)

2021-03-02 14:58 UTC, romartin commented
hey guys,

Thanks for your early review. It's still missing to complete some TODOs on a few unit tests, and also I know there are still bugs in DMN. I'm actually working on that!! 

I'll let you know once it's ready for review again. Thanks again for early reviews!!!

2021-03-08 22:08 UTC, romartin commented
Guys, just an status update - Just fixed the issue 01 and moving to the other ones. Also will complete missing tests. Soo will let you know once this is ready for review again, hopefully in a coulple of days at much... 

Thanks!

2021-03-09 23:47 UTC, romartin commented
jenkins do fdb

2021-03-10 23:00 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
> +   // TODO: Complete all below
done

2021-03-10 23:00 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/DMNDiagramEditorView.java
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
done

2021-03-10 23:00 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
done

2021-03-10 23:00 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
> +    // TODO: This was called by menus... who calls this now?
resolved

2021-03-10 23:01 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
done

2021-03-10 23:01 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
> +// TODO @RunWith(GwtMockitoTestRunner.class)
rolled-back and fixed, done!

2021-03-10 23:03 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/README.md
> +PLEASE DO NOT turn this module into a dependency for Business Central, it's ONLY targeting Kogito space.
what you mean? The goal for this POM module is just to have everything related to kogito, so just added a comment. Not sure if exist some proper and safe way to avoid adding code insided this module which depends on BC...

2021-03-10 23:07 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/editor/StunnerEditor.java
> +        if (null == getCanvasHandler().getDiagram()) {
well if the `session` is present, this class assumes the `canvasHandler` will be akways `not null`, as this class manages the session and the presenters and keeps both up to date. From the API perspective, if you call `getCanvasHandler()` it could be `null` or even throw a NPE, but because there is no `session` also

2021-03-10 23:50 UTC, romartin commented
Hey  @karreiro @jomarko  @domhanak  @danielzhe 

I've just fixed all issues (that apply) and comments from PR, also completed missing tests and TODO's!! :tada: :tada: :tada: :tada: :tada: :tada: 

About issues reported by @jomarko - **Fixed** the issues **01 and 02**, but the issues **03, 04 and 05 are not regressions**, are not introduced by this PR. I'd been analyzing and trying also to fix those. even because I didn't know they were regresstions initially, but once debugging noticed same thing happens on master; those are not trivial, and the payload for this work is never ending... so please would appreciate if we can just report 3, 04 and 05 and go ahead with this PR. WDYT?

PS: **Please would apprectiate early feedback** on this PR guys, This refactor is important, also implies LOT OF work from my side. I will be off next week and it's acutally blocking some other deverlopers work, (dmn issues & fork stuff). So please, let's be pragmatic, in case a non-blocking issue found again (hopefully not), would be nice reporting it but not holding this work any longer.

Also please if you find some other issue plz lemme know!! 

Thanks for your collaboration again!

2021-03-10 23:51 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
> +public class DMNDiagramEditorTest {
done!

2021-03-10 23:51 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommandsTest.java
> +public class DMNEditorSessionCommandsTest /*extends EditorSessionCommandsTest {
done!

2021-03-10 23:56 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/editor/StunnerEditor.java
> +public class StunnerEditor {
IMO Javadocs are not much useful... they get out of date constantly and most of the javadocs text is not usually helpping too much, long discussions I've seen around this.
Anyway, maybe on other situations it's ok, but in the case for this `StunnerEditor` type, I think the API is really clear (`open()`, `close()`, `destroy()`, etc), easy to read and to use, so don't really think it's necessary to add javadocs anyway

2021-03-10 23:57 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/editor/StunnerEditorTest.java
> +public class StunnerEditorTest {
done, there exist the tests for invalid stuff, see `testHandleParsingError` or `testHandleError`

2021-03-11 00:01 UTC, romartin commented
jenkins do fdb

2021-03-11 08:44 UTC, romartin commented
jenkins retest

2021-03-12 01:07 UTC, karreiro reviewed
Thank you, @romartin! I've tested the main scenarios and I could not find any multiple-DRD issue anymore.

However, I believe the **05** issue still happens, here's how an invalid diagram is loaded on master (notice that users can fix the diagram in the XML editor):
<img width="1470" alt="Screen Shot 2021-03-12 at 00 41 00" src="https://user-images.githubusercontent.com/1079279/110873339-d2b84700-82d1-11eb-871d-5238b790d224.png">


And here's how it appears now:
<img width="1470" alt="Screen Shot 2021-03-12 at 00 42 21" src="https://user-images.githubusercontent.com/1079279/110873326-ca600c00-82d1-11eb-8a23-76a959ac3095.png">

Also, I found these three items:

- **06** - the **kie-wb-common-dmn-webapp-kogito-testing** seems broken (I don't see it as a blocker, so it could be solved on a new PR):

<img width="1788" alt="Screenshot 2021-03-12 at 00 47 37" src="https://user-images.githubusercontent.com/1079279/110874772-a2be7300-82d4-11eb-96e5-701fa2310bf4.png">

- **07** - The editors are not getting locked when users change something in the model (the lock icon does not appear) -  (I don't see it as a blocker, so could be solved on a new PR).

- **08** - On `kie-wb-distributions`, when users open the DMN editor, and then open the BPMN editor (without closing the DMN), the editor doesn't load:

<img width="1785" alt="Screenshot 2021-03-12 at 02 00 02" src="https://user-images.githubusercontent.com/1079279/110876089-1eb9ba80-82d7-11eb-8801-717eacaa5e54.png">

I don't see most of these items as blockers (expect **08**, which is seems quite important), so I'm fine if we decide to merge this PR and solve the other issues on new ones (please let me know what you prefer, @romartin).

Thanks again!

2021-03-16 21:35 UTC, romartin commented
hey guys,

Thanks for your feedback. Honestly this PR is being a HUGE PITA for me, hard to debug and resolve all issues, but well, I'll keep trying and hopefully get into some more stable version soon

I'll work on the issues you reported @karreiro and will try to fix as much as possible, will provide feedback ASAP.
Also @caponetto yeah I noticed some issues with undo redo and other commands not working sometimes in DMN, but it looks are not regressions, those issues are also reproducible on master. I'll double cehck anyway, and let you know.

Thanks again guys, great work on reviews, and sorry for the inconveniences

2021-03-16 22:34 UTC, romartin commented
@karreiro  - my goal is trying to fix 05, 07 and 08, and maybe leave the standalone showcase fix for anotehr PR. 

Anyway, about issue 08, no way to run kie-wb-distributions (webapp) in SDM, I'm getting that `Argument list too long` error when running the maven build :(
I don't know any other showcase that includes both editors, do you? I just know about drools-wb and jbpm-wb, but their showcases are not including both editor at same time.
Any other ideas about how to the debugt the issue 08?

Thx in advance!

2021-03-16 22:46 UTC, romartin commented
@karreiro ok no worries, just noticed the sourcemaps are partially working on the generated business-central WAR , so it seems I can debug the root issue for 08... will let you know! thx anyway

2021-03-17 00:33 UTC, romartin commented
jenkins do fdb

2021-03-17 21:56 UTC, romartin commented
jenkins do fdb

2021-03-21 21:11 UTC, romartin commented
jenkins do fdb

2021-03-21 21:43 UTC, romartin commented
Hey @karreiro @jomarko  @domhanak

I finally was able to fix both issues 05 and 08 too! On the other hand, about 06 and 07, what about reporting both and fixing during next (bug fixings) weeks? 

I just propose it in order to complete this bigger task first, please notice some people depends on it, such as DMN fixes and the fork work, also because as soon as we it's on master we'll have still time for any fix that could appear.

BTW Just noticed that there is an error aobut Work Items in the BPMN Editor, but it's not produced by this PR, it's also present on master upstream, so just reported it for an eary fix too - see https://issues.redhat.com/browse/JBPM-9674

WDYT? Please could you do last test and lemme know? 

Thanks in advance, again!!!

2021-03-22 14:34 UTC, romartin commented
Hey @karreiro @jomarko @domhanak

I'm just testing the generated WAR and it looks the BPMN editor doesn't load :( Not sure if it's due to the issue reported above, please lemme test it and let you know, don't spend time testing yet please, hold on until my feedback plz.

2021-03-22 14:44 UTC, romartin commented
yes, the BPMN editor doesn't show because of the blocker, lemme at least try to fix it for showing again, although work items will be not working until we fix the blocker now (https://issues.redhat.com/browse/JBPM-9674)

2021-03-22 14:48 UTC, romartin commented
Hey @karreiro @jomarko @domhanak

So it doesn't open now because of an NPE when dealing with the exception caused by https://issues.redhat.com/browse/JBPM-9674. What I'll do is this NPE, at least to be able to test editor again because it will open, and keep that blocker issue for fixing during this week, as a new PR, does it sounds ok?

2021-03-22 15:03 UTC, romartin commented
jenkins do fdb

2021-03-22 20:52 UTC, romartin commented
Hey @karreiro @jomarko @domhanak

I just fixerd the NPE, as commented above, and tested the generated war here, so it's READY TO TEST again pleaseee, hope everythinbg will be fine.

Please appreciate early review here, deadline is this week.. thanks a lot!! :pray: :+1:

2021-03-23 15:51 UTC, karreiro reviewed
Thank you for the hard work on this, @romartin. However, I just found this issue (which seems like a blocker regression) :-(

**09** - Users cannot save a DMN model with validation errors

![2021-03-23 16 45 39](https://user-images.githubusercontent.com/1079279/112175569-a36dd800-8bf7-11eb-80d9-d34b88b8ba1a.gif)

I will continue performing tests on this PR, to check if I found anything else.

Thanks again for the hard work.

2021-03-23 16:14 UTC, jomarko commented
@romartin I rechecked my original findigs, however 2 of them are fixed, however 3 of them I can not recheck them due to 09. Not saying we need to fix 02 03 and 04 as part of this PR however is hard to report new issues properly until 09 is not fixed.

@karreiro for the record, I am not rechecking points 06, 07, 08

I can confirm 09 is issue also on my machine.

01 - fixed
02 - can not verify properly due to 09
03 - same as ^
04 - same as ^
05 - fixed

2021-03-23 20:29 UTC, romartin commented
ok thanks   @karreiro @jomarko for your review agian, really appreciated, hopefully we'll deliver an stable version after that complete testing :)
Sooo lemme fix the validation issue on DMN, once having the fix ready will let you know
Thanks!

2021-03-23 22:01 UTC, romartin commented
Hey @domhanak @karreiro @jomarko 

Thanks guys for your reviews again, and sorry for the work payload on this PR, it was not an easy one... but hopefully the benefits of this will be huge, at least on kogito, so let's keep moving :)

Sooo also fixed 09, good catch! 

At this point, thats' the status for all reported issues:
- 01 Fixed
- 02 Fixed
- 03 Not a regression introduced by this PR, we can report as a separate issue
- 04 Not a regression introduced by this PR, we can report as a separate issue
- 05 Fixed (on both kogito & BC)
- 06 Not fixed, but looks is not blocking the upstream builds and the apps will work anyway, so appreciate if we can report as a separate issue and I'll work on the fix later, but in a separate PR
- 07 Cannot reproduce, I see same behavior as on current master upstream. Anyway, if the issue exists, could we just report it as a separate issue, I can work on the fix later too
- 08 Fixed
- 09 Fixed

So not blocking issues at this point are missing, others are not introduced by this work, and there are a couple of issues that I hope we can just report as separate issues and I'll work on them, but in separate PR. Can you please do some other verification and lemme know???

Thanks again!!!

2021-03-23 22:01 UTC, romartin commented
jenkins do fdb

2021-03-24 00:31 UTC, romartin commented
jenkins retest this

2021-03-24 00:31 UTC, romartin commented
jenkins do fdb

2021-03-24 08:12 UTC, jomarko commented
@romartin from my findings 01 - 05 I found out just 04 is still reproducible and I reported as https://issues.redhat.com/browse/RHDM-1646.

Next I found still some issue blocking users from editing diagrams with multiple DRDs, Unfortunately it has 'Critical' severity from my point of view as I didn't found other workaround, than not using DRDs. Such workaround would work for new users, creating new diagrams, however users editing existing diagrams are blocked from my point of view. Reported as https://issues.redhat.com/browse/RHDM-1647

Last issue I reported is the war file size increase. War produced by downstream build in this PR produced war file 30 MB bigger than what we had on Fri 19 2021. I reported as https://issues.redhat.com/browse/RHDM-1648

The internal selenium test suite passed, however that is more sanity check than verification of all corner cases.

Due to the size of the PR and our effort to merge it on last days before cut-off, I am not able to do a code review. 

I focused just on DMN in business central. If you provide VSIX containing your changes. I can verify it also for VS Code extension.

The only scenario I tried with BPMN is using service task invoking DMN model.

2021-03-24 08:13 UTC, jomarko approved these changes

2021-03-24 09:40 UTC, hasys commented
Hi @jomarko, just my 2c about war file size. It's not clear to me from the jira description, but looks like you compare nightly VS full downstream builds. It's can't be compared since nightly do not contain client source code for debugging.

2021-03-24 10:12 UTC, jomarko commented
@hasys thank you, decreased priority and unlinked from this PR.

2021-03-24 10:54 UTC, karreiro approved these changes
Thank you for the hard work on this, @romartin. I found one last issue, but I don't think we need to solve it here. So, I reported these JIRAs:

- https://issues.redhat.com/browse/RHDM-1650
- https://issues.redhat.com/browse/KOGITO-4777

Great stuff! 🚀

2021-03-24 11:08 UTC, baldimir commented
Hi, please consider splitting this kinds of changes into 2 PRs in the future as it mixes refactoring with new code. This can cause problems in review for reviewers, making it harder for them to differentiate what is the code of the new feature and what is the refactoring code.

2021-03-24 21:36 UTC, romartin commented
Hey  @domhanak @handreyrc 

For **testing the BPMN editor** here, I just updated the artifacts, so here you can test:

- The VSIX (authoring mode) -> https://drive.google.com/file/d/142RH4X69cccBqEOfM631D2fYURMb1BIU/view?usp=sharing
- The VSIX (read only mode) -> https://drive.google.com/file/d/16T99VkBCoCI4_98pdkTtN_VyePdY_B6h/view?usp=sharing
- The Business Central artifacts will be generated by the CI builds on this PR itself

Thanks!! Let's keep in touch

2021-03-24 22:45 UTC, handreyrc commented
Hey @romartin,
I tested all functionalities around editors in both BC and kogito.

The extension works like a charm in VSCode in both modes, Authoring and ReadOnly modes. We are good here!

Regarding BC, I found some issues:

* Rename Process Error: An error popup is being displayed when you try to rename a process to "I have a new name". If you retry BC complains there's already a process with this name, however if you cancel the operation, the process is actualluy renamed.
* SequenceFlows are not displayed in readOnly mode as they are in authoring mode when checking previous versions: SequenceFlows with more than two control points are not being presented in the same way in readlonly mode as they are in authoring mode. This issue is similar to what happens in the preview panel.
* Changes in the Overview tab breaks the previous process versions: Go to the Overview tab and then edit the description field with some random text and save the process. Do the same again changing the original text in the overview tab and save process again. After that, try to load the previou version of the process.
* Export process to pdf is generating a flattened image of the process: The original dimensions of the diagram are not being preserved, the image is distorted. It works fine for all the other formats.
* Project Exprorer asset list isn't being updated properly: Create multiple processes, open one or them and then open the Project Explorer panel. Note the padlock icon idicating the opened process is locked for editing. Next, open a different process from the Explorer Panel and check it again. A padlock should be displayed before the processes locked for editing, it is not happening until the user clicks on the canvas.

Among these issues, only the first one might have been potentially introduced by this PR.

In my opinion we are good to move forward with this PR.

By the way,  excellent work!

2021-03-24 22:47 UTC, handreyrc approved these changes
Great Job! We are good to move forward with this PR.

2021-03-24 23:36 UTC, romartin commented
jenkins do fdb

2021-03-24 23:52 UTC, romartin commented
Hey @domhanak 

Here is the PR status at this point. Just missing your final review here!! :+1: 

**DMN**

Most of blocking issues fixed ( see [comment above](https://github.com/kiegroup/kie-wb-common/pull/3498#issuecomment-805295455) ), others are not introduced by this PR. So approved, although reported for further fixing (next week):
- https://issues.redhat.com/browse/RHDM-1647
- https://issues.redhat.com/browse/RHDM-1650
- https://issues.redhat.com/browse/KOGITO-4777

**BPMN**

Tested by me and  @inodeman .
Looking at [his report](https://github.com/kiegroup/kie-wb-common/pull/3498#issuecomment-806232548), only the first issue looks being introduced by this PR, and I added a comment that hopefully will fix it, otherwise I don't think that it blocks all the work behind this PR. Other issues reported are not related to this PR, so we can just report as separate JIRAs.

Sooo just missing your feedback please @domhanak ! Could you please do some verification as well? ( artifacts here )

CC @karreiro @jomarko 

BTW @caponetto @danielezonca you're actually involved on this PR too, can you please provide feedback? otherwise lemme know and I'll remove you from reviewers, np.

Thanks everyone involved here guys!

2021-03-24 23:53 UTC, romartin commented
jenkins retest this

2021-03-24 23:53 UTC, romartin commented
jenkins do fdb

2021-03-25 10:35 UTC, caponetto approved these changes
LGTM! Thanks for this huge effort, @romartin!

2021-03-25 10:36 UTC, domhanak commented
### Readonly mode for BPMN

Canvas controls limited to view-related ones (no changes persisted) - can't be verified as we do not allow
     01   Selecting elements in canvas. :heavy_check_mark: 
     02   Moving elements around canvas. :heavy_multiplication_x:  - Does not work, you can select but not move.
     03  No right-click context menu. :heavy_check_mark: 
      04   Formatting tools - to pretty align existing diagram. - Not sure what this means, but it is in acceptance criteria.
      
Properties Panels are read-only with disabled input fields. :heavy_multiplication_x: 
* Imports - user is able to open Imports and add new Data Types here. These changes are also persisted. Present after save & reopen.
![Screenshot from 2021-03-25 11-25-09](https://user-images.githubusercontent.com/5937251/112458169-ce257100-8d5c-11eb-8ad5-059e3467efb9.png)

* Notifications & Reassignments in User Tasks - DELETE and EDIT buttons are not disabled. Changes are not persisted.
![Screenshot from 2021-03-25 11-26-17](https://user-images.githubusercontent.com/5937251/112458366-ff9e3c80-8d5c-11eb-9a8c-6ad2cf2a027b.png)

* Process Variables ca have their tag edited. Just open a process with process variable and add a TAG. This is persisted.
![Screenshot from 2021-03-25 11-31-09](https://user-images.githubusercontent.com/5937251/112458967-a1258e00-8d5d-11eb-8001-59233af2ec8a.png)

These violate the acceptance criteria.

2021-03-25 10:38 UTC, domhanak requested changes
Acceptance criteria are not passed. See my previous comment.

2021-03-25 12:27 UTC, romartin commented
hey @domhanak 

About 02, it's the expected behavior - you cannot move element around when read-only.

About properties, it's out of scope from this issue, can we separat those as separate JIRAs? This PR was not fixing the forms side, was just adding the readonly parameter for kogito editors.

Given both aobve arguments, youo think could you please approve?

2021-03-25 13:18 UTC, domhanak commented
@romartin Sure, makes sense :)

02- True, I wasn't the one grooming the BAPL so I thought it is supposed to behave this way. Thanks for updating the feature description.

The properties that are still editable are reported here - https://issues.redhat.com/browse/RHPAM-3552

I will approve once I get result from execution of BPMN QE test suite.

2021-03-25 14:34 UTC, romartin commented
thanks a lot @domhanak , for both testing and reporting! Nice job guys, good to see how we moved this forrward finally, a pleasure collaborating with all of you guys!

So please @domhanak waiting for your approval, if any issues lemme know!!

thanks again for all work here guys! Hopefully we'll have a better codebase now for working on the future things :)


CC @caponetto @jomarko @karreiro

2021-03-25 23:26 UTC, romartin commented
BTW  @handreyrc - I've properly fixed the issue when renaming, which was the only one introduced by this PR. Just tested generated WAR and everything ok. Thanks! :+1:

2021-03-25 23:45 UTC, romartin commented
jenkins do fdb

2021-03-25 23:45 UTC, romartin commented
Hey @domhanak 

Just squashed everything and rebased from master. Ready for your final approval check, if no suprises :)

Thanks!

2021-03-26 00:34 UTC, romartin commented
jenkins do fdb

2021-03-26 12:40 UTC, domhanak commented
@romartin BPMN QE Test suite showed no issues. Let's merge.

2021-03-26 12:41 UTC, domhanak approved these changes

2021-03-26 14:38 UTC, merged