AF-2692 :Add a security permission to show project toolbar, Metrics tab and change request tab
kiegroup/kie-wb-common pull request #3510
Opened 2020-12-03 10:57 UTC by RishiRajAnand

**Thank you for submitting this pull request**

**AF-2690**: [AF-2690](https://issues.redhat.com/browse/AF-2690)

**Referenced Pull Requests**:
Merge with : https://github.com/kiegroup/appformer/pull/1081

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2020-12-04 08:43 UTC, tomasdavidorg requested changes

2020-12-04 08:43 UTC, tomasdavidorg commented on kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/actions/ProjectMainActionsViewImpl.java
> +    private static final String HIDDEN_CLASS = "hidden";
Not used anywhere.

2020-12-04 08:49 UTC, RishiRajAnand commented on kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/actions/ProjectMainActionsViewImpl.java
> +    private static final String HIDDEN_CLASS = "hidden";
oh, i might have missed it. Thanks

2020-12-07 15:59 UTC, paulovmr requested changes

2020-12-07 15:59 UTC, paulovmr commented on kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/actions/ProjectMainActionsViewImpl.java
> +        }
```suggestion
        this.runTests.hidden = !visible;
        this.deployBtn.hidden = !visible;
        this.buildBtn.hidden = !visible;
```

2020-12-08 05:38 UTC, RishiRajAnand commented on kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/actions/ProjectMainActionsViewImpl.java
> +        }
done

2020-12-08 06:34 UTC, tomasdavidorg approved these changes

2020-12-09 18:57 UTC, paulovmr approved these changes

2020-12-10 13:05 UTC, merged