JBPM-9385 : Stunner - Text area for scripts is cropped/shifted
kiegroup/kie-wb-common pull request #3567
Opened 2021-02-16 21:27 UTC by inodeman

Hi @romartin can you review this PR?
Adding test cases now on next commits
**Thank you for submitting this pull request**

**JIRA**: [JBPM-0000](https://issues.redhat.com/browse/JBPM-0000)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2021-02-16 21:28 UTC, inodeman commented
jenkins do fdb

2021-02-16 23:01 UTC, romartin reviewed
Hey  @inodeman 
Thanks for this work! Did a quick review on the code, plz lemme know your feedback :+1:

2021-02-16 23:01 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorPresenter.java
> +    private boolean requestRefresh = false;
mmm looks a bit tricky flag.. :) maybe if you explain why you need this we can try to figure out some other solution. Not saying it's wrong, just brainstorming

2021-02-17 18:28 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorPresenter.java
> +    public void reload() {
Hi @romartin removed

2021-02-17 18:30 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorPresenter.java
> +    private boolean requestRefresh = false;
Hi @romartin the thing is, the call to re init the monaco editor happens right now each time the user clicks a different language, I depend on the reinit of the editor to resize it according to the resize of the properties panel, so I intriduced this flag so that I can also re init it when the view requests refresh (when the resize observer gets called) let me know if anyther way

2021-02-17 20:42 UTC, inodeman commented
jenkins retest this

2021-02-17 20:42 UTC, inodeman commented
jenkins do fdb

2021-02-18 16:25 UTC, inodeman commented
jenkins retest this

2021-02-18 16:25 UTC, inodeman commented
jenkins do fdb

2021-02-23 20:59 UTC, inodeman commented
Hi @romartin @LuboTerifaj Artifacts can be found here. https://drive.google.com/drive/folders/1K1ULs_bpG_xJzBF2nPT9o_oiPdsDhJyT?usp=sharing

2021-02-24 15:58 UTC, LuboTerifaj requested changes
Hello @inodeman ,

I have found a few issues:

- Input any String to Monaco editor of any node or just change its language.
Close the properties panel or close the process.
  - Actual result: An uncaught exception occurs: `TypeError: Cannot read property 'Y1x' of null` or `TypeError: this.n is null`

- Vertical border of the editor is missing.

- If you scroll down to see the whole Monaco editor (e.g. in Service task), input any String and resize (expand) the Properties panel, the position of the main vertical scroll bar is changed. As a result, the position of displayed properties is changed. The issue applies only to Firefox.

Thanks!

2021-03-03 22:25 UTC, inodeman commented
jenkins retest this

2021-03-03 22:26 UTC, inodeman commented
jenkins do fdb

2021-03-03 23:19 UTC, inodeman commented
Hi @LuboTerifaj new artifacts can be found here. https://drive.google.com/drive/folders/1K1ULs_bpG_xJzBF2nPT9o_oiPdsDhJyT?usp=sharing I am researchig on the Firefox issue but not sure how to apply changes to only one browser. @romartin ready for review

2021-03-08 13:04 UTC, LuboTerifaj reviewed
Hello @inodeman ,

Thanks for the fixes.

There is still one remaining issue regarding changed properties position:

- If you scroll down to see the whole Monaco editor (e.g. in Service task), input any String and resize (expand) the Properties panel, the position of the main vertical scroll bar is changed. As a result, the position of displayed properties is changed. The issue applies only to Firefox.
- Note the issue above doesn't apply to Chrome, but in VSCode as well as in Chrome, there is a short "blink" of properties panel. This "animation" shouldn't be present at all.

Thanks!

2021-03-08 19:31 UTC, inodeman commented
Hi @LuboTerifaj @romartin tried to reproduce the issue but I am not unable. I mean I cannot see the difference with the current build and from what I see at https://kiegroup.github.io/kogito-online/#/editor/bpmn, is there a way you can shoot a small video to check it out, let me know

2021-03-10 20:29 UTC, inodeman commented
Hi @LuboTerifaj @romartin let me know about this, I could not reproduce the issue, maybe if ok with you we can leave as separate issue and merge, let me know

2021-03-15 14:38 UTC, romartin commented
hey @LuboTerifaj 
Thanks for the deep testing!
I'd been playing around, trying to reproduce the [issue you mention](https://github.com/kiegroup/kie-wb-common/pull/3567#pullrequestreview-606265475), and honestly I'm not able to completely reproduce it I guess.
In general works quite fine now, the editor is properly being resized on both browsers and it's possible to set the content as expected. So let's discuss now this on our weekly meeting, but I would suggest to report the other issue you mentioned, if still applies, and go ahead with this fix, which allows the proper edition.
WDYT?

2021-03-15 16:10 UTC, LuboTerifaj commented
Hello @romartin , @inodeman , 

yes, I agree the issue is not a blocker for the PR.

As we discussed on the meeting, I am adding the screenshots before and after expanding the properties panel.

Steps to reproduce:

1. Create general Service task
2. Open Properties panel and scroll down to very bottom to see the whole On Exit Action.
3. Expand the Properties panel.

#### Actual result
The main scroll bar of Properties panel is shifted. As a result, the position of properties in panel is changed.
#### Expected result 
The main scroll bar keeps its position when resizing the panel.

Before | After
------------ | -------------
![Screenshot from 2021-03-15 16-53-48](https://user-images.githubusercontent.com/12122769/111183188-f1f3f480-85af-11eb-8c61-7896339a02ce.png) | ![Screenshot from 2021-03-15 16-54-11](https://user-images.githubusercontent.com/12122769/111183191-f28c8b00-85af-11eb-98df-3e044f45e09b.png)


 If it's not easy to fix, I can report it in separate jira.  

Thanks!

2021-03-16 21:32 UTC, romartin commented
Hey   @LuboTerifaj 

Honestly I don't see an issue yet sorry :) Buuut I think I got your idea.... so when you say properties are "shifted" , it means the layout is changing, right? On the other hand, that's the expected behavior! Our properties panels are built on top of bootstrap, which automatically "shifts" components around when changing contanier size... 

Does it makes sense?

Anyway, rather than if it's an issue or not, would appreciate if you can approve this, so we can merge and keep this discussion offline, and if necessary, let's finally report the bug.

Thanks!

2021-03-18 09:57 UTC, LuboTerifaj approved these changes
Hello @romartin ,

the issue is definitely there and I cannot consider it as expected behaviour since it is different across the platforms (Chrome, VSCode, Firefox).

I've reported it here:
[JBPM-9668](https://issues.redhat.com/browse/JBPM-9668) _Properties panel expansion shifts the scrollbar_

Approving the issue.

Thanks!

2021-03-18 15:51 UTC, romartin approved these changes

2021-03-18 15:51 UTC, merged