KOGITO-4539: [DMN Designer] DMN takes too long to open models with too many nodes
kiegroup/kie-wb-common pull request #3578
Opened 2021-02-23 19:55 UTC by karreiro

**JIRA**: [KOGITO-4539](https://issues.redhat.com/browse/KOGITO-4539): [DMN Designer] DMN takes too long to open models with too many nodes

![2021-02-16 13 10 21](https://user-images.githubusercontent.com/1079279/108061341-6fcbeb00-7058-11eb-9478-7447cde39e82.gif)

**Business Central**:
- [WAR before this PR](https://www.dropbox.com/s/qd72jj9052ycdwk/KOGITO-4539-business-central-before.war?dl=0)
- [WAR after this PR](https://www.dropbox.com/s/jshovaxsvu0e1zf/KOGITO-4539-business-central-afterr.war?dl=0)

**VS Code**:
- [plugin before this PR](https://www.dropbox.com/s/1algszsvrj8mput/KOGITO-4539-before.vsix?dl=0)
- [plugin after this PR](https://www.dropbox.com/s/mf8g215kboa3mvq/KOGITO-4539-after.vsix?dl=0)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2021-02-23 20:05 UTC, karreiro commented
Jenkins do fdb.

2021-02-24 10:12 UTC, jomarko requested changes
The changes caused two decision navigator icons on left side panel and broke our selenium tests.

![Screenshot from 2021-02-24 11-11-33](https://user-images.githubusercontent.com/8044780/108985327-36ffc780-7691-11eb-80e5-733dc040d70a.png)

2021-02-24 13:35 UTC, karreiro commented
Thank you, @jomarko. I just updated the PR with the fix and with the new artifacts in the description.

2021-02-24 16:59 UTC, jomarko reviewed
Code review done, tasks to be performed during manual review as we touched `enableRefreshHandlers`, verify decision navigator is updated
- [ ] after closing
- [ ] opening other diagram
- [ ] switching tabs
- [ ] switching DRDs
- [ ] switching expression and graph editor

2021-02-24 16:59 UTC, jomarko commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorDock.java
> +        // Empty.
What does it mean `// empty` please, I think this comment does not explain enough why the implementation does nothing.

2021-02-25 17:48 UTC, karreiro commented
Thank you for the feedback, @jomarko.

I've changed my approach a little bit to avoid too many re-renders on Decision Navigator. Now, it's covering all scenarios we're targeting.

I just updated the PR with the fix and with the new artifacts in the description.

2021-02-25 18:05 UTC, karreiro commented
Jenkins do fdb.

2021-03-01 09:04 UTC, jomarko requested changes
We observe & handle same event twice.

2021-03-01 09:21 UTC, karreiro commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
> +        deferredRefresh();
Well spotted, @jomarko - thank you! I've applied the change in a new commit.

2021-03-01 09:21 UTC, karreiro commented
Jenkins do fdb.

2021-03-01 09:22 UTC, karreiro commented
Thank you, @jomarko! I've applied the change in a new commit.

2021-03-01 10:37 UTC, jomarko commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
>      }
@karreiro could you please explain why not to remove `public void onElementAdded(final @Observes CanvasElementAddedEvent event)` completely?

if I understand correctly now we call the same `refresh()` twice.
- `DecisionNavigatorObserver#onCanvasElementAdded()`
- `DecisionNavigatorPresenter#onElementAdded()`

My expectation is `DecisionNavigatorPresenter` will not contain any `@Observes CanvasElementAddedEvent event` as we observe the same and handle in same way in the `DecisionNavigatorObserver` - which is `@ApplicationScoped`. What am I missing?

2021-03-01 12:57 UTC, karreiro commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
>      }
@jomarko your understanding is correct and both methods were being triggered, but due to the defer mechanism the logic weren't being executed twice. Anyhow, both observers are redundant indeed, so I've removed `DecisionNavigatorPresenter#onElementAdded` in a new commit :-) thanks!

2021-03-01 12:57 UTC, karreiro commented
Jenkins do fdb.

2021-03-01 12:57 UTC, karreiro commented
Thank you, @jomarko! I've applied the change in a new commit.

2021-03-01 16:11 UTC, jomarko approved these changes
opening took ~30 seconds with a memory settings:
```
JAVA_OPTS="-Xms512m -Xmx2G -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=1G -Djava.net.preferIPv4Stack=true"
```
All nodes were placed correctly.

Thank you @karreiro

2021-03-01 17:23 UTC, danielzhe approved these changes
Great work!!! Thank you!

2021-03-01 17:24 UTC, merged