AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty
kiegroup/kie-wb-common pull request #3592
Opened 2021-03-12 11:05 UTC by akumar074

* Added required and readonly properties to generate variable property

**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2021-03-16 11:36 UTC, tomasdavidorg commented on kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-api/src/main/java/org/kie/workbench/common/forms/jbpm/service/bpmn/util/BPMNVariableUtils.java
> +            if(required) {
Could you please format this file?

2021-03-17 10:34 UTC, pefernan requested changes
@akumar074 would you mind add a test? 
Based on what I could see on all PR's this change only affects to HTML forms rendered on kie-server and the autogenerated forms (if no process form exists on the project). Are we considering using tags on the form generation part (generating the process forms from the bpmn editor)?

2021-04-14 08:10 UTC, tomasdavidorg approved these changes

2021-04-16 12:11 UTC, akumar074 commented
Jenkins run fdb

2021-04-16 12:11 UTC, akumar074 commented
jenkins retest this

2021-04-16 14:06 UTC, pefernan approved these changes

2021-04-19 12:50 UTC, ederign approved these changes

2021-04-19 12:51 UTC, merged