JBPM-9391 - Data Objects in Assignments disappear once the process is saved.
kiegroup/kie-wb-common pull request #3595
Opened 2021-03-22 22:40 UTC by Josephblt

It is possible to have an element loaded on the properties tab and not selected on the canvas.
The assignments widget attempts to load data objects based on that canvas item. If there is none, the error happens.
This fix uses the diagram root as the selected node for these cases.

**Thank you for submitting this pull request**

**JIRA**: [JBPM-9391](https://issues.redhat.com/browse/JBPM-9391)

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

2021-03-22 22:41 UTC, Josephblt commented
Jenkins run cdb
Jenkins run fdb

2021-03-23 00:05 UTC, Josephblt commented
Jenkins run fdb

2021-03-23 02:02 UTC, Josephblt commented
Hello @romartin, @LuboTerifaj, @domhanak. If you guys could please assign or review this, that would be great. thanks.

2021-03-26 16:26 UTC, LuboTerifaj requested changes
Hello @Josephblt ,

if you set Data Object in sub-process's User task assignment, only top level Data Object is saved.

Consider this test scenario:
![Screenshot from 2021-03-26 17-24-25](https://user-images.githubusercontent.com/12122769/112662673-3efd8380-8e58-11eb-9532-32ee6aa2736b.png)

Thanks!

2021-05-17 07:31 UTC, domhanak commented
stale PR cc @romartin

2021-05-17 13:18 UTC, romartin commented
what to do with this PR @Josephblt ? Should we go ahead and report above issues from @LuboTerifaj , if apply?

2021-05-17 13:29 UTC, Josephblt commented
Hello @romartin. I'm working on this. The problems reported by @LuboTerifaj will be fixed here. Let's keep this PR open and I'll update it.

2021-05-18 19:34 UTC, romartin commented
Hey @Josephblt 
Just talking with @inodeman and it looks we can close PR, he already used this information. Let's reopen a new PR for this ticket, once ready again. Does it makes sense?

2021-05-19 19:52 UTC, closed without merging