JBPM-9597 - [BPMN] Open subprocesses in a new editor (BC only)
kiegroup/kie-wb-common pull request #3596
Opened 2021-03-24 03:04 UTC by hasys

**JIRA**: [[BPMN] Open subprocesses in a new editor (BC only)](https://issues.redhat.com/browse/JBPM-9597)

**Business Central**: [TBD](https://donwnload.here/something)

**VS Code**: [TBD](https://donwnload.here/something)

<details>
<summary>
Hi @romartin, @domhanak, what is done:

* Toolbox button for Reusable sub-process with tool-tip to open Sub-process in Business Central only
* Error notifications
    * Sub-process ID is empty
    * Sub-process not found
* Open processes by click on the toolbox button, tested for different projects and space as well
    * Found a bug that Business Central doesn't update breadcrumbs for spaces/projects, only for process name. I think it is not related to my changes and should be fixed in Business Central itself.

Possible future change: new icon for the toolbox button.

Thank you!
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2021-03-24 03:04 UTC, hasys commented
jenkins do cdb

2021-03-24 14:33 UTC, romartin reviewed
Nice work @hasys , just added a single review comment on the code, plz confirm.
Anyway, reallly great stuff :+1:  thanks!!!

2021-03-24 14:33 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/resources/StunnerCommonIconsGlyphFactory.java
> +    ImageStripGlyph SUBPROCESS = ImageStripGlyph.create(StunnerCommonIconsStrip.class, 2);
the last integer argument shouldn't be `3` ?

2021-03-25 08:18 UTC, hasys commented
Build fail is unrelated to changes

<details>
  <summary>Stack trace</summary>
  <pre>java.lang.Exception: Error getting forked project name for kiegroup/appformer/forks?per_page=100&page=3. Communication error, please relaunch job.
	at githubscm.getForkedProjectName(githubscm.groovy:296)
	at ___cps.transform___(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor359.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:107)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor359.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:87)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor359.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE</pre>
</details>

2021-03-25 08:18 UTC, hasys commented
Jenkins retest this

2021-03-25 08:19 UTC, hasys commented
jenkins do cdb

2021-03-25 10:32 UTC, hasys commented
Fail in Compile Downstream Build is not related to the changes. Also there is successful Casc Jenkins Compile Downstream Build. So this check is passed.

<details>
  <summary>Stack trace</summary>
  <pre>09:46:30  + /home/jenkins/workspace/KIE/master/compile/kie-wb-common-master.compile/trace.sh
09:46:30  /home/jenkins/workspace/KIE/master/compile/kie-wb-common-master.compile@tmp/durable-0f218653/script.sh: line 1: /home/jenkins/workspace/KIE/master/compile/kie-wb-common-master.compile/trace.sh: No such file or directory
Error when executing failure post condition:
hudson.AbortException: script returned exit code 1
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:569)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:515)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:461)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)</pre>
</details>

2021-03-25 11:30 UTC, hasys commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/resources/StunnerCommonIconsGlyphFactory.java
> +    ImageStripGlyph SUBPROCESS = ImageStripGlyph.create(StunnerCommonIconsStrip.class, 2);
Good point @romartin, answered in the [jira issue comment](https://issues.redhat.com/browse/JBPM-9597?focusedCommentId=15998472&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15998472).

For now can we use this icon and fix it during bug fix week? It should be easy fix, just update sprite and change one digit there, so I don't expect any further risks to introduce this change later. WDYT?

cc @LuboTerifaj

2021-03-25 13:38 UTC, hasys commented
SonarCloud Gateway failed due to some new tests not counted coverage. Coverage not counted because tests failed on Jenkins CI, I can't reproduce fail locally, will investigate it now, but it looks like issue in Mocking framework in specific environments, not a real bug so it shouldn't block review process.

2021-03-25 14:30 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/resources/StunnerCommonIconsGlyphFactory.java
> +    ImageStripGlyph SUBPROCESS = ImageStripGlyph.create(StunnerCommonIconsStrip.class, 2);
sure! It makes sense to me :+1:

2021-03-25 14:30 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/resources/StunnerCommonIconsGlyphFactory.java
> +    ImageStripGlyph SUBPROCESS = ImageStripGlyph.create(StunnerCommonIconsStrip.class, 2);
if so, let's create another quick JIRA only for updateing the icon next week, ok?

2021-03-25 14:32 UTC, romartin approved these changes

2021-03-25 14:33 UTC, LuboTerifaj requested changes
Hello @hasys ,

the issues I have found:

- If you link the process in different project, after opening it, the project is not changed in breadcrumb navigation panel.

- If you link the process itself (the process where a reusable sub-process is placed), nothing happens. There could be an info message shown that the process is already open.

- The icon is the same as the icon for the generating forms in User task.

Would it be possible to fix the first and the last issue mentioned above? I can report the second one as the future enhancement if it's not implemented in this PR.

Thanks!

2021-03-25 14:43 UTC, hasys commented
Hi @LuboTerifaj,

great catches, thank you Lubo!

About fixes: 
* first one is not really related to the Designer, Designer just calling Business Central to open correct asset, so it's already on Business Central part to handle breadcrumbs correctly, I suggest to move it to separate PR, since Designer doesn't have access to this part of Business Central and should be fixed in separate repository anyway.
* Second one agree on moving it as separate issue.
* Third one is in discussion with UX team, since we don't have a proper icon yet, I suggest to merge this one since we have a deadline but we still will have time to fix icon during the bugfix period when proper icon will be delivered by the UX team. WDYT?

2021-03-25 14:53 UTC, hasys commented
About tests, I wasn't able to reproduce the issue locally but I had similar issue before with Mockito that sometimes work with package private methods where limited. I made methods public to fix mocking issue on some environments.

2021-03-25 14:54 UTC, hasys commented
jenkins do cdb

2021-03-25 15:19 UTC, LuboTerifaj commented
Hello @hasys 

regarding, the first issue, it is not directly related to Stunner, but the process is opened from editor, what is currently unexpected in Business Central and not handled properly. The issue is not visible on master, hence it should be fixed in this PR from my point of view.

However, since we don't have too much time, I agree with reporting it in separate jira in case it will be fixed in the next sprint.

What do you think?

Thanks!

2021-03-25 15:40 UTC, LuboTerifaj approved these changes
reported issues:

- [JBPM-9679](https://issues.redhat.com/browse/JBPM-9679) The processes from different projects opened from Process editor show the wrong breadcrumbs
- [JBPM-9680](https://issues.redhat.com/browse/JBPM-9680) Sub-process linked to itself doesn't perform any action 
- [JBPM-9681](https://issues.redhat.com/browse/JBPM-9681) Open sub-process icon is the same as the Forms icon

Approving.

2021-03-25 15:57 UTC, romartin commented
@hasys lemme know when it's ready to merge please!

Thanks guys!

2021-03-25 23:10 UTC, merged