RHPAM 3212 - Data Objects in Assignments disappear once the process is saved
kiegroup/kie-wb-common pull request #3603
Opened 2021-04-08 04:38 UTC by Josephblt

**JIRA**: [RHPAM 3212](https://issues.redhat.com/browse/RHPAM 3212)

**Business Central**: [WAR file](https://drive.google.com/file/d/1q8EzOTsK6Ict5osNP83Rzq_NSpeMIa_U/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1BqI0RChrmTQX8Dj_KtzahYfZp_hbTtII/view?usp=sharing)

2021-04-08 04:39 UTC, Josephblt commented
Hello @romartin. This is the correct PR. I fixed the title so we are just missing the reviewers and the review here. Thanks.

2021-04-08 04:39 UTC, Josephblt commented
Jenkins run cdb
Jenkins run fdb

2021-04-08 11:52 UTC, romartin commented
Hey @LuboTerifaj , I'm approving tihs as I'd been working with @Josephblt on this fix and I propertly tested it was working. Please need for your early review, once artifacts ready please let us know @Josephblt . This is targeting the reelease and it's an important fix, also it provides performance improvements as we're calling several itmes less the selection methods.
Thanks!

2021-04-08 11:52 UTC, romartin approved these changes

2021-04-08 12:17 UTC, Josephblt commented
Jenkins retest this

2021-04-09 05:20 UTC, Josephblt commented
Jenkins retest this

2021-04-09 12:31 UTC, LuboTerifaj commented
#3595

2021-04-09 12:32 UTC, LuboTerifaj commented
The PR on master: #3595

2021-04-09 12:43 UTC, LuboTerifaj requested changes
Hello @Josephblt , the scenario tested and mentioned here: https://github.com/kiegroup/kie-wb-common/pull/3595#pullrequestreview-622328746 is not fixed.

To reproduce the issue, set the corresponding assignment properties, save, close and open process back.

Thanks!

2021-04-09 13:41 UTC, romartin commented
Hey @Josephblt 
Please can you check @LuboTerifaj 's avobe comments?
Thanks!

2021-04-26 20:40 UTC, romartin commented
Hey @LuboTerifaj @Josephblt I think this PR, which targets `7.52.x` branch, can be now closed.This will end up on master stream, once fixed. Am I correct?

2021-04-28 17:41 UTC, closed without merging