KOGITO-4919: [DMN Designer] SDM is broken on -kogito-webapp-runtime
kiegroup/kie-wb-common pull request #3611
Opened 2021-04-13 14:38 UTC by karreiro

**JIRA**: [KOGITO-4919](https://issues.redhat.com/browse/KOGITO-4919): [DMN Designer] SDM is broken on -kogito-webapp-runtime

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2021-04-13 17:51 UTC, danielzhe approved these changes

2021-04-13 18:22 UTC, romartin approved these changes

2021-04-13 20:33 UTC, romartin requested changes
Hey @karreiro 

I have this fix locally, and it works for `kie-wb-common`, but now trying to build `drools-wb`, it fails because of:

`[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.9.0:compile (gwt-compile) on project drools-wb-webapp: GWT Module org.kie.dmn.feel.gwt.functions.DMNFeelGWTFunctions not found in project sources or resources. -> [Help 1]
`
So maybe some fix on some pom is still necessary... I understand if `drools-wb `doesn't compile, also `kie-wb-distributions` will not compile... any clues?

2021-04-13 20:41 UTC, romartin commented
jenkins retest this

2021-04-13 20:44 UTC, romartin reviewed
Another issue found, look at my comment below. By not changing the scope for the sources artifact,  maybe then everything works... will let to you guys to test it, I'm still with the issue on DMN too.

Thanks!

2021-04-13 20:44 UTC, romartin commented on kie-wb-common-dmn/kie-wb-common-dmn-client/pom.xml
> +      <scope>provided</scope>
@karreiro also not sure if makes sense this change - when classifier is `sources`, I think doesn't make sense to use the `provided` scope. The sources are only necessary for the gwt compiler, so the artifact is needed at compile scope, so making it runtime makes things not work.

2021-04-14 09:23 UTC, karreiro commented
Thank you, @romartin! :-) Changes applied.

2021-04-14 11:54 UTC, romartin commented
@karreiro just checked out the branch again and the SDM for webapp-kogito-runtime does't work now :( 
Same issues as initially, libraries are ending up in the web-inf/lib again and jetty doesn't start

2021-04-14 14:16 UTC, romartin commented
jenkins do fdb

2021-04-14 14:36 UTC, romartin approved these changes
Hey @karreiro 

Tested both DMN for webapp-kogito-runtime and also drools-wb-webapp (WAR, not SDM), both apps working properly. So looks good to me!! Thanks again for the fixes, great job! :+1:

2021-04-14 17:32 UTC, karreiro commented
jenkins do fdb

2021-04-15 08:18 UTC, karreiro commented
jenkins do fdb

2021-04-15 13:17 UTC, karreiro commented
jenkins do fdb

2021-04-16 09:36 UTC, karreiro commented
@romartin @danielzhe I just incorporated I small-new commit to fix a CI error.

2021-04-16 09:39 UTC, karreiro commented
jenkins do fdb

2021-04-16 10:20 UTC, karreiro commented
jenkins retest this

2021-04-16 13:39 UTC, karreiro commented
jenkins do fdb

2021-04-16 18:24 UTC, danielzhe commented
I'm not 100% sure, but I think this fix broke the regular DMN Showcase. Can you try to run DMN Showcase with this fix applied? By showcase I mean 'kie-wb-common-dmn-webapp-standalone'. @karreiro

2021-04-19 12:15 UTC, karreiro commented
Thank you, @danielzhe! Double-checking it :-)

2021-04-19 13:26 UTC, karreiro commented
jenkins do fdb

2021-04-19 14:17 UTC, karreiro commented
@danielzhe fixes applied, the branch is rebased, and ready for the re-review :-)

2021-04-19 20:11 UTC, danielzhe approved these changes
It's fixed now! Thank you, @karreiro !

2021-04-20 07:08 UTC, karreiro commented
jenkins do fdb

2021-04-20 16:02 UTC, karreiro commented
jenkins do fdb

2021-04-21 06:59 UTC, karreiro commented
jenkins do fdb

2021-04-21 14:29 UTC, karreiro commented
jenkins do fdb

2021-04-22 07:03 UTC, merged