JBPM-9874 - bpmndi:BPMNShape id of intermediateCatchEvent is always set to 'shape_null'
kiegroup/kie-wb-common pull request #3705
Opened 2021-11-20 02:02 UTC by Josephblt

The shape was created while the base element ID was null.
The method execution order was changed to ensure the ID is set before use.

**JIRA**: [JBPM-9874](https://issues.redhat.com/browse/JBPM-9874)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here

**Business Central**: [WAR file](https://donwnload.here/something)

2021-11-20 17:43 UTC, Josephblt commented
Jenkins do cdb
Jenkins do fdb

2021-11-23 13:06 UTC, Josephblt commented
Jen
Jenkins do cdb

2021-11-23 13:06 UTC, Josephblt commented
Jenkins do cdb

2021-11-25 12:41 UTC, hasys approved these changes
Thank you @Josephblt, I tested the WAR file and it works good now. Great job!

2021-12-13 14:29 UTC, LuboTerifaj requested changes
Hello @Josephblt ,

unfortunately the issue is not fixed. Follow the steps to reproduce in [JBPM-9874](https://issues.redhat.com/browse/JBPM-9874) jira and see server.log. It contains messages similar to this one:
```
ERROR [org.drools.core.xml.ExtensibleXmlParser] (EJB default - 1) Node Info: id:message1Type name: 
Parser message: (null: 3, 60): cvc-datatype-valid.1.2.1: '' is not a valid value for 'QName'.
```
Thanks!

2021-12-13 14:43 UTC, hasys commented
Hi @LuboTerifaj,

your message means that there is missing Message property value which is correct.

So just fill Message property and issue will disappear.

This is expected behavior.

Thank you!

2021-12-13 15:13 UTC, LuboTerifaj requested changes
Hello @hasys , the message property in the process is set, but the error message in server.log is still present.

2021-12-13 15:21 UTC, Josephblt commented
Hello @LuboTerifaj. Could you please add your .bpmn to the JIRA?

2021-12-13 16:11 UTC, LuboTerifaj commented
Hello @Josephblt , sure, I have added Signals-process.bpmn to upstream jira.

2021-12-22 14:27 UTC, LuboTerifaj approved these changes
Hello @Josephblt , @hasys 

I have reported the issue I mentioned in my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3705#pullrequestreview-830310162) above here:
[JBPM-9981](https://issues.redhat.com/browse/JBPM-9981) _Error message in log when using signal without Data Assignment_

It looks good to me then.

Thank you!

2021-12-22 14:31 UTC, hasys commented
@kiegroup/gatekeepers pr is ready for merge. Thank you!

2021-12-22 15:03 UTC, merged