KOGITO-4647 : [DMN] FEEL client-side - Remove mirror classes
kiegroup/kie-wb-common pull request #3712
Opened 2021-12-07 13:27 UTC by Rikkola

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2021-12-13 09:01 UTC, jomarko approved these changes

2021-12-13 09:16 UTC, jomarko requested changes
**kie-wb-common-dmn-webapp-standalone**

Caused by: org.jboss.errai.codegen.exception.UndefinedMethodException: undefined method: setAccessible(java.lang.Boolean); in class: java.lang.reflect.Method
16:05:43  [ERROR] 	at org.jboss.errai.codegen.builder.callstack.MethodCall.handleCall(MethodCall.java:84)
16:05:43  [ERROR] 	... 32 more
16:05:43  [INFO]             [ERROR] Error gene

2022-01-31 11:35 UTC, Rikkola commented
jenkins retest this

2022-01-31 11:36 UTC, Rikkola commented
@jomarko fixed. [Here is a war if you want to try this out. I guess just if anything on code completition is broken or not.](https://drive.google.com/file/d/1UUwHAdd3oux-8Cl9OVZQoJXl-S81w1HG/view?usp=sharing)

2023-05-24 09:40 UTC, closed without merging