JBPM-10083: Legacy (jBPM) Process Designer Removal
kiegroup/kie-wb-common pull request #3743
Opened 2022-07-08 18:47 UTC by inodeman

**Thank you for submitting this pull request**

**JIRA**: [JBPM-10083](https://issues.redhat.com/browse/JBPM-10083)

**Referenced Pull Requests**:
https://github.com/kiegroup/kie-wb-distributions/pull/1168
(Removes JBPM-Designer module from kie-wb-distributions

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2022-07-08 18:59 UTC, inodeman commented
iHi @romartin can you review this PR?
For testing, you just need to verify that the old jbpm-designer module is removed. Basically if you have bpmn2 files you wont be able to open them using the old designer, instead stunner will open up and give you the choice to migrate it, if you choose not to it will open an XML Editor for you, it will also open up the XML Editor if any issues during the migration, for instance if the file already exists.

2022-07-20 21:59 UTC, romartin commented
Hey @LuboTerifaj 

This PR it is a top priority for the release. Could you please prioritize it properly and take a look as soon as possible plz?
Remember it is related to https://github.com/kiegroup/kie-wb-distributions/pull/1168

Thanks in advance!

2022-07-20 22:09 UTC, romartin reviewed
Hey @inodeman 

Thanks for this work, looks great stuff overall! I checked code for now, just added a few review comments. Please let me know what you think.

Thanks!

2022-07-20 22:09 UTC, romartin commented on kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock
> +"@kie/lock-treatment-tool@^0.1.0":
hey @inodeman 

I don't think all changes this `yarn.lock` file must be commited. Can you please verify why you got these changes as part of your work, and drop this commited file, if applies?

THx!

2022-07-20 22:09 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/util/XMLDisplayerData.java
> +    private String xml;
As this is a portable object between the server and clients, can this `xml` field be `final` as well? It has some implications on performance, and it's a good practice. I had been looking and looks that you don't really use the setter more than once, so I think it should be feasible to make the field final. WDYT?

2022-07-20 22:09 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/util/XMLDisplayerData.java
> +    private Metadata metadata;
same here, would be good making this field `final`, as above one.

2022-07-20 22:09 UTC, romartin commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
> +                throw new RuntimeException("File [" + n + "] should have the suffix [" + ext + "]");
Not really sure how `RuntimeException` instance is being handled on top of the workbench, but it may end up on crashing the whole page. Can you please reach thsi line and see how the UI behaves? If applies, refactor this by calling some error callback or just logging it, at worst, in order to not make UI to crash.

2022-07-21 17:27 UTC, inodeman commented on kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock
> +"@kie/lock-treatment-tool@^0.1.0":
Hi @romartin remove the change

2022-07-21 17:28 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/util/XMLDisplayerData.java
> +    private String xml;
Hi @romartin you are right, should be final, will make the change

2022-07-21 17:31 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/util/XMLDisplayerData.java
> +    private Metadata metadata;
Hi @romartin making them both final

2022-07-21 17:39 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
> +                throw new RuntimeException("File [" + n + "] should have the suffix [" + ext + "]");
Hi @romartin you are right, changing it to log the error

2022-07-21 18:39 UTC, inodeman commented
Hi @romartin changes are in and new War generated for testing

2022-07-22 12:58 UTC, LuboTerifaj commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/resource/BPMNDefinitionSetResourceType.java
> +    }
What the "second" means here? Does it mean the one going after another, or just the other option of the prefix?

Why did you use "prefix" in the method names and not the "suffix"?

2022-07-22 17:29 UTC, LuboTerifaj requested changes
Hello @inodeman ,

The point from Acceptance criteria defined in jira is not fulfilled:

- "After successful migration, legacy bpmn2 asset is **not shown among other assets**, but it is still visible in Project explorer."

Here are the issues I found:

- If you open a legacy process without migration in the xml editor, the name in the title has the **wrong extension**.
  - There should be bpmn2 instead of bpmn since the process has not been migrated yet.

- If you migrate the legacy process to Stunner, open both processes (do not close the Stunner and **open xml editor** for legacy one), open Properties panel or Explore Diagram, the **Stunner panel is opened** instead of empty panel.
  - This might be caused by the previous issue mentioned above.

- There is **a loading wheel** shown below the migration pop-up window.
  - It would be great to remove it.

- **Xml editor is not opened** when you try to migrate the corrupted legacy process or interupt the migration with not supported elements in Stunner editor.
  - Loading wheel with the message is shown.
  - It is **not possible to interact with Business Central** at all.

- If you deploy the project with a legacy process, the process **diagram in proc definitions or instances is not shown**.
  - The following message is shown: `Process diagram not found. Deployment container project_1.0.0-SNAPSHOT must be available and started.`
  - There is a warning message shown in server.log: `WARN  [org.kie.server.services.jbpm.ui.ImageServiceBase] (default task-16) Could not find SVG image file for process 'src.legacy-process' within container project_1.0.0-SNAPSHOT`.
  - It would be great to have the specific message about not supporting legacy Designer in Business Central. The server log may contain the warning message mentioned above since it contains useful information.
  - What do you think about this issue? Do you have any ideas how to deal with it?
	
- In Settings -> Roles/Groups -> Editors -> Add Exception, there is shown "(New) jBPM Designer Editor" in the list.
  - I think **"New" is redundant** here and it doesn't make sense any more.

- Mortgage_Process project **sample has BPMN2** in the description.
  - Description: "_Getting started loan approval process in BPMN2, decision table, business rules, and forms._"

Possible enhancement:
- If user clicks cancel when migration pop-up window is shown and decides to migrate the process afterwards, they have to close and open the process (xml editor) to show the migration pop-up once again.
  - It would be great to have the option to **migrate the legacy processes** also **directly from the xml editor**.
  - A dedicated migration button could be added there when the files with bpmn2 extension are open.

Please also check my inline comments regarding code.

Thank you!

2022-07-25 14:23 UTC, romartin commented
> Hello @inodeman ,
> 
> The point from Acceptance criteria defined in jira is not fulfilled:
> 
> * "After successful migration, legacy bpmn2 asset is **not shown among other assets**, but it is still visible in Project explorer."

Agree, we must change the acceptance criteria, thx

> 
> Here are the issues I found:
> 
> * If you open a legacy process without migration in the xml editor, the name in the title has the **wrong extension**.
>   
>   * There should be bpmn2 instead of bpmn since the process has not been migrated yet.

Please @inodeman analyze this

> * If you migrate the legacy process to Stunner, open both processes (do not close the Stunner and **open xml editor** for legacy one), open Properties panel or Explore Diagram, the **Stunner panel is opened** instead of empty panel.
>   
>   * This might be caused by the previous issue mentioned above.

Please @inodeman analyze this

> * There is **a loading wheel** shown below the migration pop-up window.
>   
>   * It would be great to remove it.

Please @inodeman analyze this

> * **Xml editor is not opened** when you try to migrate the corrupted legacy process or interupt the migration with not supported elements in Stunner editor.
>   
>   * Loading wheel with the message is shown.
>   * It is **not possible to interact with Business Central** at all.

Please @inodeman fix this

> * If you deploy the project with a legacy process, the process **diagram in proc definitions or instances is not shown**.
>   
>   * The following message is shown: `Process diagram not found. Deployment container project_1.0.0-SNAPSHOT must be available and started.`
>   * There is a warning message shown in server.log: `WARN  [org.kie.server.services.jbpm.ui.ImageServiceBase] (default task-16) Could not find SVG image file for process 'src.legacy-process' within container project_1.0.0-SNAPSHOT`.
>   * It would be great to have the specific message about not supporting legacy Designer in Business Central. The server log may contain the warning message mentioned above since it contains useful information.

Please @LuboTerifaj  can you manage this doc stuff plz?

>   * What do you think about this issue? Do you have any ideas how to deal with it?
> * In Settings -> Roles/Groups -> Editors -> Add Exception, there is shown "(New) jBPM Designer Editor" in the list.
>   
>   * I think **"New" is redundant** here and it doesn't make sense any more.

Please @inodeman change this to "Process Designer Editor"

> * Mortgage_Process project **sample has BPMN2** in the description.
>   
>   * Description: "_Getting started loan approval process in BPMN2, decision table, business rules, and forms._"
> 
> Possible enhancement:
> 

Nothing to do here

> * If user clicks cancel when migration pop-up window is shown and decides to migrate the process afterwards, they have to close and open the process (xml editor) to show the migration pop-up once again.
>   
>   * It would be great to have the option to **migrate the legacy processes** also **directly from the xml editor**.
>   * A dedicated migration button could be added there when the files with bpmn2 extension are open.
> 
> Please also check my inline comments regarding code.
> 

Nothing to do here

> Thank you!

2022-07-26 11:11 UTC, LuboTerifaj commented
Hello @romartin ,

I have updated the AC.

Sure, I will let the doc team know regarding the issue with process definitions and instances diagram.

Regarding the last two points from my previous [review](https://github.com/kiegroup/kie-wb-common/pull/3743#pullrequestreview-1047868367), I agree that no action is needed.

Thanks!

2022-07-27 18:19 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/resource/BPMNDefinitionSetResourceType.java
> +    }
Hi @LuboTerifaj you are right, will change to suffix, second suffix means bpmn2, I had to configure it so that it would support bpmn and bpmn2 files

2022-07-27 18:20 UTC, inodeman commented on kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/definition/AbstractDefinitionSetResourceType.java
> +    }
Hi @LuboTerifaj basically it means it can support bpmn (first suffix) and bpmn2 (second suffix)

2022-07-27 19:58 UTC, romartin commented
Thanks @LuboTerifaj ! Looks good :)

2022-07-28 20:14 UTC, inodeman commented
Hi @LuboTerifaj @romartin uploading the new War to https://drive.google.com/drive/folders/195afqwca3fw7Bg-48wK3XmSa7bxJCRtD?usp=sharing
Most of the issues have been fixed, except for the properties/explorer dock issue, I have added code so that when the XML editor opens up it closes both of those docks, but if you open them again you will see the content from the bpmn file, so far I have not been able to find a solution, commented with @romartin and he said we might not be able to do it

Also, on the issues about the exception, now if it detects any warnings or errors it will open the XML editor, this way the UI wont become unusable, if the user has some warning and he proceeds to migrate and is successful, the XML editor will close up

Let me know

2022-08-01 11:39 UTC, LuboTerifaj commented
Hello @inodeman , I can't see any new commits, but I tested the war you provided.

The only issue I found is: "Properties panel contains data from other processes".

I recommend to fix the issue in this PR since it is possible to edit properties of other processes when you open legacy process in Xml editor. It shouldn't be possible to do that.
Actually, the properties panel is not supposed to be displayed at all, but at least it should be empty.
	
Steps to reproduce:
  1. Migrate legacy process or just open any Stunner process.
  2. Do not close the process.
  3. Open legacy process in Xml editor and open Properties panel.

Thanks!

2022-08-01 14:44 UTC, inodeman commented
Hi @LuboTerifaj sorry, I had not pushed my changes, they are in now. Thanks

2022-08-01 15:49 UTC, LuboTerifaj approved these changes
Hello @inodeman ,

as discussed on the call, I have reported the last not resolved issue here: https://issues.redhat.com/browse/JBPM-10104

I didn't find any other issues.

Thank you!

2022-08-02 10:42 UTC, romartin approved these changes

2022-08-02 10:42 UTC, romartin commented
Thanks @LuboTerifaj @inodeman 

BTW @inodeman can you please check why not all checks are on green?

2022-08-02 13:22 UTC, romartin commented
Hey @inodeman 

Three test cases are failing. Please a fix is necessary.

2022-08-02 14:55 UTC, LuboTerifaj commented
Hello @inodeman , @romartin  there is one bug reported by sonar and there is also insufficient test coverage.

2022-08-02 15:14 UTC, inodeman commented
Hi @romartin, seems the 3 tests are from DMN and it was because of the Garbage collector, dont think it is related as the Java 11 all passed.

2022-08-02 15:17 UTC, inodeman commented
Hi @LuboTerifaj, I did see the bug, but it is mainly a HTML convention, when I tried to fix it the component did not behave as we want, basically it says to add <legend> tag, but we dont need that, will look at the test coverage you mention, hi @romartin what do you think about the bug mentioned?, here is a screenshot. BTW, I brought this file from appformer, since the one from it was not notifying if the user clicked cancel.
![image](https://user-images.githubusercontent.com/39567766/182410306-b5b6c503-2e59-4cae-a464-7b77d474d955.png)

2022-08-02 20:09 UTC, inodeman commented
Hi @romartin @LuboTerifaj I have added test coverage as much as I could, there are some classes where sonarcloud for some reason does not count the tests correctly, see AbstractVFSDiagramService, the test class is abstract and another class ends up executing them, but they are not counted, I did add a couple more to that class but will not count, other classes are basic classes for example BPMNDefinitionSetResourceType it says there should be tests there but in the past we have never included tests for these classes, lastly, there are some scenarios where I have to check if something is null to exclude the code to be executed from tests, because there are not defined classes in test scope. As I mentioned did the best I could to increase the coverage but I dont think it will get up to 80%, also see my previous comment about the bug mentioned by sonar cloud. Will upload War shortly.

2022-08-02 20:22 UTC, inodeman commented
Hi @romartin @LuboTerifaj new War will be uploaded here. https://drive.google.com/drive/folders/195afqwca3fw7Bg-48wK3XmSa7bxJCRtD?usp=sharing

2022-08-03 10:31 UTC, mareknovotny commented
shouldn't those changes be send to ONLY 7.67.x-blue branch? @lazarotti

2022-08-03 11:25 UTC, LuboTerifaj commented
Hello @inodeman , 

Regarding the bug, why the one tag changes the component behaviour? Is it hard to fix it? If yes, I am okay with letting it be as it is. 

Regarding test coverage, it looks good to me.

Thanks!

2022-08-03 15:10 UTC, romartin commented
@mareknovotny please see https://github.com/kiegroup/kie-wb-distributions/pull/1168#issuecomment-1204076901

2022-08-03 17:54 UTC, inodeman commented
Hi @LuboTerifaj yes, if I add the <legend> tag, then I would have to do something else since the labels are already there, this component is based on a component from uberfire which does it the way I have it. Let me know

2022-08-03 17:55 UTC, inodeman commented
jenkins do bdb

2022-08-03 17:56 UTC, inodeman commented
Jenkins run full downstream build

2022-08-03 17:57 UTC, inodeman commented
Jenkins retest this

2022-08-03 17:57 UTC, inodeman commented
Jenkins run fdb

2022-08-03 20:37 UTC, romartin commented
hey @mareknovotny @lazarotti 

You know guys If we can feel free to merge this PR, although there are still some unrelated CI build issues? (they're due to timeouts or memory issues). Are you up to date with the status of the CI for this repo?

This is a top priority PR that we should merge ASAP. WDYT? Can we go ahead? Re-fire the builds? Please NOTICE it is related to https://github.com/kiegroup/kie-wb-distributions/pull/1168 , which is also faliing on the CI

thx!

2022-08-03 20:38 UTC, romartin commented
hey @mareknovotny @lazarotti 

You know guys If we can feel free to merge this PR, although there are still some unrelated CI build issues? (they're due to timeouts or memory issues). Are you up to date with the status of the CI for this repo?

This is a top priority PR that we should merge ASAP. WDYT? Can we go ahead? Re-fire the builds? Please NOTICE it is related to https://github.com/kiegroup/kie-wb-distributions/pull/1168 , which is also faliing on the CI

thx!

2022-08-03 20:38 UTC, romartin commented
@mbiarnes any feedback here please?? ^^

2022-08-04 09:36 UTC, mareknovotny commented
jenkins do fdb

2022-08-04 09:38 UTC, mareknovotny commented
relaunched CI on https://github.com/kiegroup/kie-wb-distributions/pull/1168, start FDB here.

Btw shouldn't we remove now also https://github.com/kiegroup/jbpm-designer from all CI and FDB builds? @romartin @inodeman

2022-08-04 13:26 UTC, romartin commented
@mareknovotny good Q! IMO I think we can remove the [jbpm-designer](https://github.com/kiegroup/jbpm-designer ) from the CI builds, not removing the repo tiself, but al least dropping this module from the build pipeline. Are you agree as well?

@mareknovotny if so, can you please point us where to drop this module from the config files, in oder to skip it from CI?

2022-08-04 13:46 UTC, romartin commented
as from @mareknovotny feedback, in oder to drop legacy-designer from CI pipeline:

CI project deps are declared in https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/.ci/project-dependencies.yaml, but we can ask someone in my team to do changes if you are blind in this area

Can you please @inodeman try to drop it fro mthe config files? Then we'll make sure, in the CI build logs, that it is not being part of the build anymore...

Thanks!

2022-08-04 13:46 UTC, romartin commented
thanks @mareknovotny , good catch!

2022-08-04 13:51 UTC, mareknovotny commented
cc @Ginxo @mbiarnes to review or help with dropping of jbpm-designer repository from CI

2022-08-05 10:53 UTC, Ginxo commented
@romartin @mareknovotny In order to properly test this PR, same owner and branch names should be applied to the CI changes. So I propose to guide @inodeman to apply it but he/she/* will have to open please, do you agree?

- Remove from project-dependencies.yaml
  - https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/4dd77daecc8794a467f8d8ed6b50922a3db39736/.ci/project-dependencies.yaml#L138
  - https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/4dd77daecc8794a467f8d8ed6b50922a3db39736/.ci/project-dependencies.yaml#L151
- the one from repository-list.txt will be automatically adapted once PR is merged https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/d27d7d4ea07a4d4376c70efd0a5570888d957703/script/repository-list.txt#L15
- kie-parent pom:
  - to remove property from pom https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/1e63b164c89a3ea8aceff89054567d44faa006a5/pom.xml#L301
  - should we remove these dependencies? 
    - https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/4c263b24fed769df496f63d977199ef677788db1/jbpm-bom/pom.xml#L679
    - https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/4c263b24fed769df496f63d977199ef677788db1/jbpm-bom/pom.xml#L702
-  from README https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/fd132db5c686ae7a9c18e6f5b58ec80b65767532/RELEASE-README.md?plain=1#L25
- from Jenkins jobs perspective. Should we keep them? otherwise we won't cover old branches for jbpm-designer
  - https://github.com/kiegroup/kie-jenkins-scripts/blob/6d37dcff5315ffdff4893151ea173ef4a71d32cb/job-dsls/jobs/kie/main/downstream_production.groovy
  - https://github.com/kiegroup/kie-jenkins-scripts/blob/240b9a19e77f6bab97944bf039f47aaa0a884a94/job-dsls/jobs/kie/main/compile_downstream_build.groovy
  - https://github.com/kiegroup/kie-jenkins-scripts/blob/240b9a19e77f6bab97944bf039f47aaa0a884a94/job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
  - https://github.com/kiegroup/kie-jenkins-scripts/blob/240b9a19e77f6bab97944bf039f47aaa0a884a94/job-dsls/jobs/kie/main/pr_jobs.groovy
  - https://github.com/kiegroup/kie-jenkins-scripts/blob/4cfecd251963228b5075752dd4eb0a91acabd868/job-dsls/jobs/kie/main/deploy_jobs.groovy
  - https://github.com/kiegroup/kie-jenkins-scripts/blob/main/job-dsls/jobs/kie/main/pr_jobs.groovy

2022-08-05 12:24 UTC, mareknovotny commented
there is not needed to keep old branches to work with original repo list as we should back port this to 7.67.x and 7.67.x-blue too. Of course the backport would need to follow closely to not break it meanwhile it is broken.

2022-08-05 19:06 UTC, inodeman commented
Hi @Ginxo thanks, will follow up on that, my only concern is that if I remove some references from POM the build will fail, but will test each case

2022-08-09 13:11 UTC, romartin commented
thanks @mareknovotny for pointing this out! Yeah we'll do the backport to `7.67.x` and `7.67.x-blue `as well!, @inodeman is working on it.

2022-08-09 13:17 UTC, romartin commented
Hey @mareknovotny , still facing this build issue: `You have exceeded a secondary rate limit. Please wait a few minutes before you try again.`

I can't see any other error related to this PR rather than the one above. You know what's the status for the CI? I can see some PR in this repo on green, but most and newer on red again, any ideas?

Thx in advance!

2022-08-09 13:23 UTC, mareknovotny commented
@Ginxo @mbiarnes see the reported github rate limit?

2022-08-09 13:37 UTC, mareknovotny commented
where do you see it @romartin ?

2022-08-09 13:39 UTC, mbiarnes commented
Jenkins retest this

2022-08-09 13:45 UTC, mbiarnes commented
Jenkins run fdb

2022-08-09 22:44 UTC, romartin commented
@mareknovotny look at the `Build Chain / ubuntu-latest - Java 8` details link, then look at the `build chain` section in the log, and you'll see this error at the end: `You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
`
I am not sure if that's the root cause of the failures, but I can't see in other tasks any error related to this PR.

2022-08-09 22:58 UTC, romartin commented
@mbiarnes @mareknovotny  @inodeman 

Sorry guys, thanks to @mbiarnes , I just found the root issue, which is due to a compilation error in the code on this PR!  Sorry for the inconveniences!

```

16:37:58  [ERROR] COMPILATION ERROR : 
16:37:58  [INFO] -------------------------------------------------------------
16:37:58  [ERROR] /home/jenkins/workspace/KIE/main/fdb/kie-wb-common-main.fdb/bc/kiegroup_jbpm_designer/jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java:[266,64] method migrateFromJBPMDesignerToStunner in interface org.kie.workbench.common.stunner.bpmn.integration.client.IntegrationHandler cannot be applied to given types;
16:37:58    required: org.uberfire.backend.vfs.Path,org.uberfire.mvp.PlaceRequest,boolean,org.uberfire.mvp.ParameterizedCommand<java.util.function.Consumer<java.lang.Boolean>>,org.uberfire.mvp.Command,org.uberfire.mvp.Command,org.uberfire.mvp.Command
16:37:58    found: org.uberfire.backend.vfs.ObservablePath,org.uberfire.mvp.PlaceRequest,boolean,(saveCallb[...]rue))
16:37:58    reason: actual and formal argument lists differ in length
16:37:58  [INFO] 1 error
16:37:58  [INFO] -------------------------------------------------------------

```
Please @inodeman , can you fix this compilation error and re-fire the builds? If any error persists, please look at the FULL LOG for the build task, and starting from the end of the document, scroll up looking for the root cause.

2022-08-10 16:12 UTC, inodeman commented
Jenkins run fdb

2022-08-10 19:11 UTC, inodeman commented
Jenkins retest this

2022-08-10 19:11 UTC, inodeman commented
Jenkins run fdb

2022-08-11 10:35 UTC, romartin commented
Jenkins run fdb

2022-08-11 16:38 UTC, inodeman commented
Hi @mareknovotny @mbiarnes I made some changes yesterday and been triggered the fdb but after many hours it has hanged twice, it is currently hanged, not sure if I should retrigger it or what is the issue, could you point me in the right direction?

2022-08-11 19:16 UTC, romartin commented
@mareknovotny @mbiarnes @cristianonicolai 

Hey guys, we see now the Ci failing in the `jBPM WB showcase`, this is the root cause I can find:
`  Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.errai.marshalling.rebind.DefinitionsFactorySingleton"}}}}`

Can you please help on fixing this?

Thanks!

2022-08-12 13:54 UTC, mareknovotny commented
that should by fixed by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023 and downgrading JDK to 11.0.2 on our build nodes.

2022-08-16 16:35 UTC, inodeman commented
Jenkins run fdb

2022-08-16 16:43 UTC, inodeman commented
Thanks @mareknovotny trying it now

2022-08-17 07:38 UTC, mareknovotny commented
jenkins do fdb

i resolved merging conflict on [kie](https://github.com/kiegroup/kie-wb-distributions/pull/1168)

2022-08-17 13:38 UTC, mareknovotny commented
jenkins do fdb

2022-08-17 18:14 UTC, inodeman commented
Hi @mareknovotny saw these issues on latest build. Will refire the builds
![image](https://user-images.githubusercontent.com/39567766/185212658-05419ec9-07d3-42db-905f-083db98c675e.png)

2022-08-17 18:15 UTC, inodeman commented
jenkins do fdb

2022-08-18 07:53 UTC, merged